# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_credito_calcular.ui'
#
# Created: Mon Dec  5 16:10:11 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_credito_calcular(object):
    def setupUi(self, form_credito_calcular):
        form_credito_calcular.setObjectName("form_credito_calcular")
        form_credito_calcular.resize(671, 607)
        form_credito_calcular.setStyleSheet("selection-background-color: rgb(218, 175, 158);\n"
"selection-color: rgb(0, 0, 0);\n"
"font:  75 10Pt \"Century Schoolbook L\";")
        self.tabWidget = QtWidgets.QTabWidget(form_credito_calcular)
        self.tabWidget.setGeometry(QtCore.QRect(10, 7, 651, 591))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(172, 55, 26);\n"
"font:  75 10Pt \"Century Schoolbook L\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 631, 541))
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lne_cta_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_13.setGeometry(QtCore.QRect(130, 40, 113, 23))
        self.lne_cta_13.setObjectName("lne_cta_13")
        self.lne_cta_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_14.setGeometry(QtCore.QRect(130, 70, 113, 23))
        self.lne_cta_14.setObjectName("lne_cta_14")
        self.lne_cta_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_15.setGeometry(QtCore.QRect(130, 100, 113, 23))
        self.lne_cta_15.setObjectName("lne_cta_15")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 280, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 310, 101, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 340, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 370, 101, 16))
        self.label_12.setObjectName("label_12")
        self.lne_cta_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_16.setGeometry(QtCore.QRect(130, 130, 113, 23))
        self.lne_cta_16.setObjectName("lne_cta_16")
        self.lne_cta_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_17.setGeometry(QtCore.QRect(130, 160, 113, 23))
        self.lne_cta_17.setObjectName("lne_cta_17")
        self.lne_cta_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_18.setGeometry(QtCore.QRect(130, 190, 113, 23))
        self.lne_cta_18.setObjectName("lne_cta_18")
        self.lne_cta_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_19.setGeometry(QtCore.QRect(130, 220, 113, 23))
        self.lne_cta_19.setObjectName("lne_cta_19")
        self.lne_cta_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_20.setGeometry(QtCore.QRect(130, 250, 113, 23))
        self.lne_cta_20.setObjectName("lne_cta_20")
        self.lne_cta_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_21.setGeometry(QtCore.QRect(130, 280, 113, 23))
        self.lne_cta_21.setObjectName("lne_cta_21")
        self.lne_cta_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_22.setGeometry(QtCore.QRect(130, 310, 113, 23))
        self.lne_cta_22.setObjectName("lne_cta_22")
        self.lne_cta_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_23.setGeometry(QtCore.QRect(130, 340, 113, 23))
        self.lne_cta_23.setObjectName("lne_cta_23")
        self.lne_cta_24 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_24.setGeometry(QtCore.QRect(130, 370, 113, 23))
        self.lne_cta_24.setObjectName("lne_cta_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(360, 30, 59, 15))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(360, 60, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(360, 90, 81, 16))
        self.label_27.setObjectName("label_27")
        self.lne_capital = QtWidgets.QLineEdit(self.tab_2)
        self.lne_capital.setGeometry(QtCore.QRect(460, 30, 113, 23))
        self.lne_capital.setObjectName("lne_capital")
        self.lne_cant_cta = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cant_cta.setGeometry(QtCore.QRect(460, 60, 113, 23))
        self.lne_cant_cta.setObjectName("lne_cant_cta")
        self.lne_valor_cta = QtWidgets.QLineEdit(self.tab_2)
        self.lne_valor_cta.setGeometry(QtCore.QRect(460, 90, 113, 23))
        self.lne_valor_cta.setObjectName("lne_valor_cta")
        self.boton_calcular = QtWidgets.QPushButton(self.tab_2)
        self.boton_calcular.setGeometry(QtCore.QRect(460, 130, 80, 23))
        self.boton_calcular.setObjectName("boton_calcular")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/calculadora.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_2, icon, "")
        self.tabWidget.addTab(self.tab, icon, "")

        self.retranslateUi(form_credito_calcular)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_credito_calcular)

    def retranslateUi(self, form_credito_calcular):
        _translate = QtCore.QCoreApplication.translate
        form_credito_calcular.setWindowTitle(_translate("form_credito_calcular", "Calcular Crédito"))
        self.label.setText(_translate("form_credito_calcular", "13 Cuotas de $"))
        self.label_2.setText(_translate("form_credito_calcular", "14 Cuotas de $"))
        self.label_3.setText(_translate("form_credito_calcular", "16 Cuotas de $"))
        self.label_4.setText(_translate("form_credito_calcular", "19 Cuotas de $"))
        self.label_5.setText(_translate("form_credito_calcular", "18 Cuotas de $"))
        self.label_6.setText(_translate("form_credito_calcular", "17 Cuotas de $"))
        self.label_7.setText(_translate("form_credito_calcular", "15 Cuotas de $"))
        self.label_8.setText(_translate("form_credito_calcular", "20 Cuotas de $"))
        self.label_9.setText(_translate("form_credito_calcular", "21 Cuotas de $"))
        self.label_10.setText(_translate("form_credito_calcular", "22 Cuotas de $"))
        self.label_11.setText(_translate("form_credito_calcular", "23 Cuotas de $"))
        self.label_12.setText(_translate("form_credito_calcular", "24 Cuotas de $"))
        self.label_25.setText(_translate("form_credito_calcular", "Capital:"))
        self.label_26.setText(_translate("form_credito_calcular", "N * Cuotas :"))
        self.label_27.setText(_translate("form_credito_calcular", "Valor Cuota :"))
        self.boton_calcular.setText(_translate("form_credito_calcular", "Calcular"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("form_credito_calcular", "Calcular"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_credito_calcular", "Cálculo de Crédito"))

