# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_clientes_borrar.ui'
#
# Created: Fri Feb 24 11:27:22 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_clientes_borrar(object):
    def setupUi(self, Form_clientes_borrar):
        Form_clientes_borrar.setObjectName("Form_clientes_borrar")
        Form_clientes_borrar.resize(1020, 720)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form_clientes_borrar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form_clientes_borrar)
        self.tabWidget.setStyleSheet("selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgba(136, 3, 3, 100);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_121 = QtWidgets.QLabel(self.tab)
        self.label_121.setStyleSheet("font: 75 10pt \"KacstOne\";")
        self.label_121.setObjectName("label_121")
        self.horizontalLayout.addWidget(self.label_121)
        self.lne_dni_filtro_borrar = QtWidgets.QLineEdit(self.tab)
        self.lne_dni_filtro_borrar.setMinimumSize(QtCore.QSize(100, 22))
        self.lne_dni_filtro_borrar.setMaximumSize(QtCore.QSize(150, 22))
        self.lne_dni_filtro_borrar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_dni_filtro_borrar.setObjectName("lne_dni_filtro_borrar")
        self.horizontalLayout.addWidget(self.lne_dni_filtro_borrar)
        self.boton_buscar_borrar = QtWidgets.QPushButton(self.tab)
        self.boton_buscar_borrar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"font: 75 10pt \"KacstOne\";")
        self.boton_buscar_borrar.setObjectName("boton_buscar_borrar")
        self.horizontalLayout.addWidget(self.boton_buscar_borrar)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.groupBox = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox.setGeometry(QtCore.QRect(3, 17, 941, 421))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.tab_16)
        self.layoutWidget.setGeometry(QtCore.QRect(19, 240, 911, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_131 = QtWidgets.QLabel(self.layoutWidget)
        self.label_131.setObjectName("label_131")
        self.verticalLayout.addWidget(self.label_131)
        self.txte_observaciones_4 = QtWidgets.QTextEdit(self.layoutWidget)
        self.txte_observaciones_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txte_observaciones_4.setObjectName("txte_observaciones_4")
        self.verticalLayout.addWidget(self.txte_observaciones_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_16)
        self.layoutWidget1.setGeometry(QtCore.QRect(19, 38, 911, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_133 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_2.addWidget(self.label_133)
        self.lne_apellido_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_apellido_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_apellido_buscar_2.setObjectName("lne_apellido_buscar_2")
        self.horizontalLayout_2.addWidget(self.lne_apellido_buscar_2)
        self.label_124 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_124.setObjectName("label_124")
        self.horizontalLayout_2.addWidget(self.label_124)
        self.lne_nombre_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_nombre_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre_buscar_2.setObjectName("lne_nombre_buscar_2")
        self.horizontalLayout_2.addWidget(self.lne_nombre_buscar_2)
        self.label_128 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_128.setObjectName("label_128")
        self.horizontalLayout_2.addWidget(self.label_128)
        self.lne_nro_cliente_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_nro_cliente_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_cliente_buscar_2.setObjectName("lne_nro_cliente_buscar_2")
        self.horizontalLayout_2.addWidget(self.lne_nro_cliente_buscar_2)
        self.ckbx_activo_buscar_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckbx_activo_buscar_2.setObjectName("ckbx_activo_buscar_2")
        self.horizontalLayout_2.addWidget(self.ckbx_activo_buscar_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_127 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_127.setObjectName("label_127")
        self.horizontalLayout_3.addWidget(self.label_127)
        self.cbx_tipo_doc_buscar_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbx_tipo_doc_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_tipo_doc_buscar_2.setObjectName("cbx_tipo_doc_buscar_2")
        self.cbx_tipo_doc_buscar_2.addItem("")
        self.cbx_tipo_doc_buscar_2.addItem("")
        self.cbx_tipo_doc_buscar_2.addItem("")
        self.horizontalLayout_3.addWidget(self.cbx_tipo_doc_buscar_2)
        self.label_130 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_130.setObjectName("label_130")
        self.horizontalLayout_3.addWidget(self.label_130)
        self.lne_nro_doc_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_nro_doc_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_doc_buscar_2.setObjectName("lne_nro_doc_buscar_2")
        self.horizontalLayout_3.addWidget(self.lne_nro_doc_buscar_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ckbx_inactivo_buscar_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ckbx_inactivo_buscar_2.setObjectName("ckbx_inactivo_buscar_2")
        self.horizontalLayout_3.addWidget(self.ckbx_inactivo_buscar_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_122 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_122.setObjectName("label_122")
        self.horizontalLayout_4.addWidget(self.label_122)
        self.dte_nacimiento_buscar_2 = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dte_nacimiento_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_nacimiento_buscar_2.setDate(QtCore.QDate(1945, 5, 17))
        self.dte_nacimiento_buscar_2.setObjectName("dte_nacimiento_buscar_2")
        self.horizontalLayout_4.addWidget(self.dte_nacimiento_buscar_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_125 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_4.addWidget(self.label_125)
        self.cbx_estado_civil_buscar_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbx_estado_civil_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_estado_civil_buscar_2.setObjectName("cbx_estado_civil_buscar_2")
        self.cbx_estado_civil_buscar_2.addItem("")
        self.cbx_estado_civil_buscar_2.addItem("")
        self.cbx_estado_civil_buscar_2.addItem("")
        self.cbx_estado_civil_buscar_2.addItem("")
        self.horizontalLayout_4.addWidget(self.cbx_estado_civil_buscar_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_135 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_135.setObjectName("label_135")
        self.horizontalLayout_5.addWidget(self.label_135)
        self.lne_domicilio_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_domicilio_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio_buscar_2.setObjectName("lne_domicilio_buscar_2")
        self.horizontalLayout_5.addWidget(self.lne_domicilio_buscar_2)
        self.label_123 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_123.setObjectName("label_123")
        self.horizontalLayout_5.addWidget(self.label_123)
        self.lne_barrio_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_barrio_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_barrio_buscar_2.setObjectName("lne_barrio_buscar_2")
        self.horizontalLayout_5.addWidget(self.lne_barrio_buscar_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_126 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_126.setObjectName("label_126")
        self.horizontalLayout_6.addWidget(self.label_126)
        self.lne_telfono_buscar_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_telfono_buscar_2.setMinimumSize(QtCore.QSize(100, 22))
        self.lne_telfono_buscar_2.setMaximumSize(QtCore.QSize(150, 22))
        self.lne_telfono_buscar_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_telfono_buscar_2.setObjectName("lne_telfono_buscar_2")
        self.horizontalLayout_6.addWidget(self.lne_telfono_buscar_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.label_134 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_134.setObjectName("label_134")
        self.horizontalLayout_6.addWidget(self.label_134)
        self.cbx_ciudad_4 = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbx_ciudad_4.setMinimumSize(QtCore.QSize(150, 22))
        self.cbx_ciudad_4.setMaximumSize(QtCore.QSize(175, 22))
        self.cbx_ciudad_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ciudad_4.setObjectName("cbx_ciudad_4")
        self.cbx_ciudad_4.addItem("")
        self.horizontalLayout_6.addWidget(self.cbx_ciudad_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_132 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_132.setObjectName("label_132")
        self.horizontalLayout_7.addWidget(self.label_132)
        self.lne_limite_credito_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_limite_credito_4.setMinimumSize(QtCore.QSize(100, 22))
        self.lne_limite_credito_4.setMaximumSize(QtCore.QSize(100, 22))
        self.lne_limite_credito_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_limite_credito_4.setObjectName("lne_limite_credito_4")
        self.horizontalLayout_7.addWidget(self.lne_limite_credito_4)
        self.label_129 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_129.setObjectName("label_129")
        self.horizontalLayout_7.addWidget(self.label_129)
        self.lne_email_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lne_email_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_email_4.setObjectName("lne_email_4")
        self.horizontalLayout_7.addWidget(self.lne_email_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/tarjeta-personal-de-datos-de-contacto.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_16, icon, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_2.setGeometry(QtCore.QRect(3, 10, 941, 411))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget2.setGeometry(QtCore.QRect(79, 100, 487, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_137 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_137.setObjectName("label_137")
        self.horizontalLayout_10.addWidget(self.label_137)
        self.lne_telefono_laboral_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lne_telefono_laboral_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_telefono_laboral_4.setObjectName("lne_telefono_laboral_4")
        self.horizontalLayout_10.addWidget(self.lne_telefono_laboral_4)
        self.label_143 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_143.setObjectName("label_143")
        self.horizontalLayout_10.addWidget(self.label_143)
        self.lne_categoria_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lne_categoria_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_categoria_4.setText("")
        self.lne_categoria_4.setObjectName("lne_categoria_4")
        self.horizontalLayout_10.addWidget(self.lne_categoria_4)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget3.setGeometry(QtCore.QRect(79, 130, 452, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_140 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_140.setObjectName("label_140")
        self.horizontalLayout_11.addWidget(self.label_140)
        self.lne_domicilio_laboral_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lne_domicilio_laboral_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio_laboral_4.setObjectName("lne_domicilio_laboral_4")
        self.horizontalLayout_11.addWidget(self.lne_domicilio_laboral_4)
        self.ckbx_recibo_sueldo_4 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.ckbx_recibo_sueldo_4.setChecked(True)
        self.ckbx_recibo_sueldo_4.setObjectName("ckbx_recibo_sueldo_4")
        self.horizontalLayout_11.addWidget(self.ckbx_recibo_sueldo_4)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget4.setGeometry(QtCore.QRect(79, 70, 549, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_138 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_138.setObjectName("label_138")
        self.horizontalLayout_9.addWidget(self.label_138)
        self.lne_organismo_4 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lne_organismo_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_organismo_4.setObjectName("lne_organismo_4")
        self.horizontalLayout_9.addWidget(self.lne_organismo_4)
        self.label_141 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_141.setObjectName("label_141")
        self.horizontalLayout_9.addWidget(self.label_141)
        self.lne_antiguedad_4 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lne_antiguedad_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_antiguedad_4.setText("")
        self.lne_antiguedad_4.setObjectName("lne_antiguedad_4")
        self.horizontalLayout_9.addWidget(self.lne_antiguedad_4)
        self.label_142 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_142.setObjectName("label_142")
        self.horizontalLayout_9.addWidget(self.label_142)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_17)
        self.layoutWidget5.setGeometry(QtCore.QRect(79, 40, 436, 31))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_139 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_139.setObjectName("label_139")
        self.horizontalLayout_8.addWidget(self.label_139)
        self.lne_ocupacion_4 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lne_ocupacion_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lne_ocupacion_4.setObjectName("lne_ocupacion_4")
        self.horizontalLayout_8.addWidget(self.lne_ocupacion_4)
        self.label_136 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_136.setObjectName("label_136")
        self.horizontalLayout_8.addWidget(self.label_136)
        self.lne_sueldo_4 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lne_sueldo_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_sueldo_4.setText("")
        self.lne_sueldo_4.setObjectName("lne_sueldo_4")
        self.horizontalLayout_8.addWidget(self.lne_sueldo_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/hombre-en-el-escritorio-de-la-oficina-con-un-ordenador.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_17, icon1, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 931, 541))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_154 = QtWidgets.QLabel(self.groupBox_3)
        self.label_154.setObjectName("label_154")
        self.horizontalLayout_12.addWidget(self.label_154)
        self.lne_garante_apellido_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_apellido_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_apellido_4.setObjectName("lne_garante_apellido_4")
        self.horizontalLayout_12.addWidget(self.lne_garante_apellido_4)
        self.label_153 = QtWidgets.QLabel(self.groupBox_3)
        self.label_153.setObjectName("label_153")
        self.horizontalLayout_12.addWidget(self.label_153)
        self.lne_garante_nombre_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nombre_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nombre_4.setObjectName("lne_garante_nombre_4")
        self.horizontalLayout_12.addWidget(self.lne_garante_nombre_4)
        self.label_156 = QtWidgets.QLabel(self.groupBox_3)
        self.label_156.setObjectName("label_156")
        self.horizontalLayout_12.addWidget(self.label_156)
        self.lne_garante_nro_cliente_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_cliente_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nro_cliente_4.setObjectName("lne_garante_nro_cliente_4")
        self.horizontalLayout_12.addWidget(self.lne_garante_nro_cliente_4)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_12.addWidget(self.checkBox_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_150 = QtWidgets.QLabel(self.groupBox_3)
        self.label_150.setObjectName("label_150")
        self.horizontalLayout_13.addWidget(self.label_150)
        self.cbx_garante_tipo_doc_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.cbx_garante_tipo_doc_4.setObjectName("cbx_garante_tipo_doc_4")
        self.cbx_garante_tipo_doc_4.addItem("")
        self.cbx_garante_tipo_doc_4.addItem("")
        self.cbx_garante_tipo_doc_4.addItem("")
        self.horizontalLayout_13.addWidget(self.cbx_garante_tipo_doc_4)
        self.label_145 = QtWidgets.QLabel(self.groupBox_3)
        self.label_145.setObjectName("label_145")
        self.horizontalLayout_13.addWidget(self.label_145)
        self.lne_garante_nro_doc_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_doc_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nro_doc_4.setObjectName("lne_garante_nro_doc_4")
        self.horizontalLayout_13.addWidget(self.lne_garante_nro_doc_4)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_13.addWidget(self.checkBox_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_148 = QtWidgets.QLabel(self.groupBox_3)
        self.label_148.setObjectName("label_148")
        self.horizontalLayout_14.addWidget(self.label_148)
        self.dte_garante_nacimiento_4 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dte_garante_nacimiento_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_garante_nacimiento_4.setDate(QtCore.QDate(1945, 5, 17))
        self.dte_garante_nacimiento_4.setObjectName("dte_garante_nacimiento_4")
        self.horizontalLayout_14.addWidget(self.dte_garante_nacimiento_4)
        self.label_152 = QtWidgets.QLabel(self.groupBox_3)
        self.label_152.setObjectName("label_152")
        self.horizontalLayout_14.addWidget(self.label_152)
        self.cbx_garante_ciudad_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.cbx_garante_ciudad_4.setObjectName("cbx_garante_ciudad_4")
        self.cbx_garante_ciudad_4.addItem("")
        self.horizontalLayout_14.addWidget(self.cbx_garante_ciudad_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_157 = QtWidgets.QLabel(self.groupBox_3)
        self.label_157.setObjectName("label_157")
        self.horizontalLayout_15.addWidget(self.label_157)
        self.lne_garante_domicilio_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_domicilio_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_domicilio_4.setObjectName("lne_garante_domicilio_4")
        self.horizontalLayout_15.addWidget(self.lne_garante_domicilio_4)
        self.label_151 = QtWidgets.QLabel(self.groupBox_3)
        self.label_151.setObjectName("label_151")
        self.horizontalLayout_15.addWidget(self.label_151)
        self.lne_garante_barrio_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_barrio_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_barrio_4.setObjectName("lne_garante_barrio_4")
        self.horizontalLayout_15.addWidget(self.lne_garante_barrio_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_146 = QtWidgets.QLabel(self.groupBox_3)
        self.label_146.setObjectName("label_146")
        self.horizontalLayout_16.addWidget(self.label_146)
        self.lne__garante_telefono_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne__garante_telefono_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne__garante_telefono_4.setObjectName("lne__garante_telefono_4")
        self.horizontalLayout_16.addWidget(self.lne__garante_telefono_4)
        self.label_147 = QtWidgets.QLabel(self.groupBox_3)
        self.label_147.setObjectName("label_147")
        self.horizontalLayout_16.addWidget(self.label_147)
        self.lne_garante_email_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_email_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_email_4.setObjectName("lne_garante_email_4")
        self.horizontalLayout_16.addWidget(self.lne_garante_email_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_149 = QtWidgets.QLabel(self.groupBox_3)
        self.label_149.setObjectName("label_149")
        self.horizontalLayout_17.addWidget(self.label_149)
        self.lne_garante_limite_credito_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_limite_credito_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_limite_credito_4.setObjectName("lne_garante_limite_credito_4")
        self.horizontalLayout_17.addWidget(self.lne_garante_limite_credito_4)
        self.label_155 = QtWidgets.QLabel(self.groupBox_3)
        self.label_155.setObjectName("label_155")
        self.horizontalLayout_17.addWidget(self.label_155)
        self.cbx_garante_estado_civil_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.cbx_garante_estado_civil_4.setObjectName("cbx_garante_estado_civil_4")
        self.cbx_garante_estado_civil_4.addItem("")
        self.cbx_garante_estado_civil_4.addItem("")
        self.cbx_garante_estado_civil_4.addItem("")
        self.cbx_garante_estado_civil_4.addItem("")
        self.horizontalLayout_17.addWidget(self.cbx_garante_estado_civil_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_144 = QtWidgets.QLabel(self.groupBox_3)
        self.label_144.setObjectName("label_144")
        self.verticalLayout_3.addWidget(self.label_144)
        self.txte_garante_observaciones_4 = QtWidgets.QTextEdit(self.groupBox_3)
        self.txte_garante_observaciones_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txte_garante_observaciones_4.setObjectName("txte_garante_observaciones_4")
        self.verticalLayout_3.addWidget(self.txte_garante_observaciones_4)
        self.boton_agregar_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_agregar_4.setObjectName("boton_agregar_4")
        self.verticalLayout_3.addWidget(self.boton_agregar_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tw_garantes_lista_4 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tw_garantes_lista_4.setObjectName("tw_garantes_lista_4")
        self.tw_garantes_lista_4.setColumnCount(10)
        self.tw_garantes_lista_4.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Descargas/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon2)
        self.tw_garantes_lista_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.tw_garantes_lista_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.tw_garantes_lista_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista_4.setHorizontalHeaderItem(9, item)
        self.gridLayout.addWidget(self.tw_garantes_lista_4, 1, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Íconos/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_18, icon3, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_4.setGeometry(QtCore.QRect(3, 10, 481, 281))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_161 = QtWidgets.QLabel(self.groupBox_4)
        self.label_161.setObjectName("label_161")
        self.horizontalLayout_18.addWidget(self.label_161)
        self.lne_iva_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_iva_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_iva_4.setObjectName("lne_iva_4")
        self.horizontalLayout_18.addWidget(self.lne_iva_4)
        self.rbt_monotributista_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbt_monotributista_4.setObjectName("rbt_monotributista_4")
        self.horizontalLayout_18.addWidget(self.rbt_monotributista_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_158 = QtWidgets.QLabel(self.groupBox_4)
        self.label_158.setObjectName("label_158")
        self.horizontalLayout_19.addWidget(self.label_158)
        self.lne_cuit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cuit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit_4.setObjectName("lne_cuit_4")
        self.horizontalLayout_19.addWidget(self.lne_cuit_4)
        self.ckbx_facturas_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_facturas_4.setChecked(True)
        self.ckbx_facturas_4.setObjectName("ckbx_facturas_4")
        self.horizontalLayout_19.addWidget(self.ckbx_facturas_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_159 = QtWidgets.QLabel(self.groupBox_4)
        self.label_159.setObjectName("label_159")
        self.horizontalLayout_20.addWidget(self.label_159)
        self.lne_cbu_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cbu_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cbu_4.setObjectName("lne_cbu_4")
        self.horizontalLayout_20.addWidget(self.lne_cbu_4)
        self.ckbx_veraz_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_veraz_4.setChecked(True)
        self.ckbx_veraz_4.setObjectName("ckbx_veraz_4")
        self.horizontalLayout_20.addWidget(self.ckbx_veraz_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_160 = QtWidgets.QLabel(self.groupBox_4)
        self.label_160.setObjectName("label_160")
        self.horizontalLayout_21.addWidget(self.label_160)
        self.lne_nro_beneficio_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_nro_beneficio_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_beneficio_4.setObjectName("lne_nro_beneficio_4")
        self.horizontalLayout_21.addWidget(self.lne_nro_beneficio_4)
        self.ckbx_jub_pens_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_jub_pens_4.setObjectName("ckbx_jub_pens_4")
        self.horizontalLayout_21.addWidget(self.ckbx_jub_pens_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.ckbx_bloqueado_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_bloqueado_4.setObjectName("ckbx_bloqueado_4")
        self.verticalLayout_6.addWidget(self.ckbx_bloqueado_4)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Íconos/casilla-y-boligrafo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_19, icon4, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Íconos/basura.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon5, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.pushButton_3 = QtWidgets.QPushButton(Form_clientes_borrar)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 101, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_3.setPalette(palette)
        self.pushButton_3.setStyleSheet("background-color: rgb(235, 160, 143);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_22.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(Form_clientes_borrar)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 142, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 67, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 50, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 160, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 101, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_2.setPalette(palette)
        self.pushButton_2.setStyleSheet("background-color: rgb(235, 160, 143);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_22.addWidget(self.pushButton_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)

        self.retranslateUi(Form_clientes_borrar)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form_clientes_borrar)
        Form_clientes_borrar.setTabOrder(self.tabWidget, self.lne_dni_filtro_borrar)
        Form_clientes_borrar.setTabOrder(self.lne_dni_filtro_borrar, self.boton_buscar_borrar)
        Form_clientes_borrar.setTabOrder(self.boton_buscar_borrar, self.tabWidget_2)
        Form_clientes_borrar.setTabOrder(self.tabWidget_2, self.lne_apellido_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_apellido_buscar_2, self.lne_nombre_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_nombre_buscar_2, self.lne_nro_cliente_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_nro_cliente_buscar_2, self.ckbx_activo_buscar_2)
        Form_clientes_borrar.setTabOrder(self.ckbx_activo_buscar_2, self.cbx_tipo_doc_buscar_2)
        Form_clientes_borrar.setTabOrder(self.cbx_tipo_doc_buscar_2, self.lne_nro_doc_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_nro_doc_buscar_2, self.ckbx_inactivo_buscar_2)
        Form_clientes_borrar.setTabOrder(self.ckbx_inactivo_buscar_2, self.dte_nacimiento_buscar_2)
        Form_clientes_borrar.setTabOrder(self.dte_nacimiento_buscar_2, self.cbx_estado_civil_buscar_2)
        Form_clientes_borrar.setTabOrder(self.cbx_estado_civil_buscar_2, self.lne_domicilio_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_domicilio_buscar_2, self.lne_barrio_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_barrio_buscar_2, self.lne_telfono_buscar_2)
        Form_clientes_borrar.setTabOrder(self.lne_telfono_buscar_2, self.cbx_ciudad_4)
        Form_clientes_borrar.setTabOrder(self.cbx_ciudad_4, self.lne_limite_credito_4)
        Form_clientes_borrar.setTabOrder(self.lne_limite_credito_4, self.lne_email_4)
        Form_clientes_borrar.setTabOrder(self.lne_email_4, self.txte_observaciones_4)
        Form_clientes_borrar.setTabOrder(self.txte_observaciones_4, self.lne_ocupacion_4)
        Form_clientes_borrar.setTabOrder(self.lne_ocupacion_4, self.lne_sueldo_4)
        Form_clientes_borrar.setTabOrder(self.lne_sueldo_4, self.lne_organismo_4)
        Form_clientes_borrar.setTabOrder(self.lne_organismo_4, self.lne_antiguedad_4)
        Form_clientes_borrar.setTabOrder(self.lne_antiguedad_4, self.lne_telefono_laboral_4)
        Form_clientes_borrar.setTabOrder(self.lne_telefono_laboral_4, self.lne_categoria_4)
        Form_clientes_borrar.setTabOrder(self.lne_categoria_4, self.lne_domicilio_laboral_4)
        Form_clientes_borrar.setTabOrder(self.lne_domicilio_laboral_4, self.ckbx_recibo_sueldo_4)
        Form_clientes_borrar.setTabOrder(self.ckbx_recibo_sueldo_4, self.lne_garante_apellido_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_apellido_4, self.lne_garante_nombre_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_nombre_4, self.lne_garante_nro_cliente_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_nro_cliente_4, self.checkBox_10)
        Form_clientes_borrar.setTabOrder(self.checkBox_10, self.cbx_garante_tipo_doc_4)
        Form_clientes_borrar.setTabOrder(self.cbx_garante_tipo_doc_4, self.lne_garante_nro_doc_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_nro_doc_4, self.checkBox_11)
        Form_clientes_borrar.setTabOrder(self.checkBox_11, self.dte_garante_nacimiento_4)
        Form_clientes_borrar.setTabOrder(self.dte_garante_nacimiento_4, self.cbx_garante_ciudad_4)
        Form_clientes_borrar.setTabOrder(self.cbx_garante_ciudad_4, self.lne_garante_domicilio_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_domicilio_4, self.lne_garante_barrio_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_barrio_4, self.lne__garante_telefono_4)
        Form_clientes_borrar.setTabOrder(self.lne__garante_telefono_4, self.lne_garante_email_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_email_4, self.lne_garante_limite_credito_4)
        Form_clientes_borrar.setTabOrder(self.lne_garante_limite_credito_4, self.cbx_garante_estado_civil_4)
        Form_clientes_borrar.setTabOrder(self.cbx_garante_estado_civil_4, self.txte_garante_observaciones_4)
        Form_clientes_borrar.setTabOrder(self.txte_garante_observaciones_4, self.boton_agregar_4)
        Form_clientes_borrar.setTabOrder(self.boton_agregar_4, self.tw_garantes_lista_4)
        Form_clientes_borrar.setTabOrder(self.tw_garantes_lista_4, self.lne_iva_4)
        Form_clientes_borrar.setTabOrder(self.lne_iva_4, self.rbt_monotributista_4)
        Form_clientes_borrar.setTabOrder(self.rbt_monotributista_4, self.lne_cuit_4)
        Form_clientes_borrar.setTabOrder(self.lne_cuit_4, self.ckbx_facturas_4)
        Form_clientes_borrar.setTabOrder(self.ckbx_facturas_4, self.lne_cbu_4)
        Form_clientes_borrar.setTabOrder(self.lne_cbu_4, self.ckbx_veraz_4)
        Form_clientes_borrar.setTabOrder(self.ckbx_veraz_4, self.lne_nro_beneficio_4)
        Form_clientes_borrar.setTabOrder(self.lne_nro_beneficio_4, self.ckbx_jub_pens_4)
        Form_clientes_borrar.setTabOrder(self.ckbx_jub_pens_4, self.ckbx_bloqueado_4)
        Form_clientes_borrar.setTabOrder(self.ckbx_bloqueado_4, self.pushButton_2)
        Form_clientes_borrar.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, Form_clientes_borrar):
        _translate = QtCore.QCoreApplication.translate
        Form_clientes_borrar.setWindowTitle(_translate("Form_clientes_borrar", "Form"))
        self.label_121.setText(_translate("Form_clientes_borrar", "DNI:"))
        self.boton_buscar_borrar.setText(_translate("Form_clientes_borrar", "Buscar"))
        self.label_131.setText(_translate("Form_clientes_borrar", "Observaciones: "))
        self.label_133.setText(_translate("Form_clientes_borrar", "Apellido:"))
        self.lne_apellido_buscar_2.setText(_translate("Form_clientes_borrar", "Fernandez"))
        self.label_124.setText(_translate("Form_clientes_borrar", "Nombre :"))
        self.lne_nombre_buscar_2.setText(_translate("Form_clientes_borrar", "Alejandro"))
        self.label_128.setText(_translate("Form_clientes_borrar", "N°  Cliente :"))
        self.lne_nro_cliente_buscar_2.setText(_translate("Form_clientes_borrar", "00-001"))
        self.ckbx_activo_buscar_2.setText(_translate("Form_clientes_borrar", "Activo"))
        self.label_127.setText(_translate("Form_clientes_borrar", "Tipo Documento:"))
        self.cbx_tipo_doc_buscar_2.setItemText(0, _translate("Form_clientes_borrar", "DNI "))
        self.cbx_tipo_doc_buscar_2.setItemText(1, _translate("Form_clientes_borrar", "CUIL"))
        self.cbx_tipo_doc_buscar_2.setItemText(2, _translate("Form_clientes_borrar", "CUIT "))
        self.label_130.setText(_translate("Form_clientes_borrar", "Número:"))
        self.lne_nro_doc_buscar_2.setText(_translate("Form_clientes_borrar", "5678879"))
        self.ckbx_inactivo_buscar_2.setText(_translate("Form_clientes_borrar", "Inactivo"))
        self.label_122.setText(_translate("Form_clientes_borrar", "Fecha de Nacimiento:"))
        self.dte_nacimiento_buscar_2.setDisplayFormat(_translate("Form_clientes_borrar", "yyyy/M/dd"))
        self.label_125.setText(_translate("Form_clientes_borrar", "Estado Civil:"))
        self.cbx_estado_civil_buscar_2.setItemText(0, _translate("Form_clientes_borrar", "Soltero/era"))
        self.cbx_estado_civil_buscar_2.setItemText(1, _translate("Form_clientes_borrar", "Casado/ada"))
        self.cbx_estado_civil_buscar_2.setItemText(2, _translate("Form_clientes_borrar", "Viudo/da"))
        self.cbx_estado_civil_buscar_2.setItemText(3, _translate("Form_clientes_borrar", "Divorsiado/ada"))
        self.label_135.setText(_translate("Form_clientes_borrar", "Domicilio :"))
        self.lne_domicilio_buscar_2.setText(_translate("Form_clientes_borrar", "Las violestas 68"))
        self.label_123.setText(_translate("Form_clientes_borrar", "Barrio:"))
        self.lne_barrio_buscar_2.setText(_translate("Form_clientes_borrar", "Las flores"))
        self.label_126.setText(_translate("Form_clientes_borrar", "Teléfono:"))
        self.lne_telfono_buscar_2.setText(_translate("Form_clientes_borrar", "2920-000001"))
        self.label_134.setText(_translate("Form_clientes_borrar", "Ciudad:"))
        self.cbx_ciudad_4.setItemText(0, _translate("Form_clientes_borrar", "Viedma"))
        self.label_132.setText(_translate("Form_clientes_borrar", "Límite por Créditos:"))
        self.lne_limite_credito_4.setText(_translate("Form_clientes_borrar", "10000"))
        self.label_129.setText(_translate("Form_clientes_borrar", "Email:"))
        self.lne_email_4.setText(_translate("Form_clientes_borrar", "email@email.com"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_16), _translate("Form_clientes_borrar", "Datos Personales"))
        self.label_137.setText(_translate("Form_clientes_borrar", "Teléfono Laboral:"))
        self.lne_telefono_laboral_4.setText(_translate("Form_clientes_borrar", "2920-000001"))
        self.label_143.setText(_translate("Form_clientes_borrar", "Categoría: "))
        self.label_140.setText(_translate("Form_clientes_borrar", "Domicilio Laboral:"))
        self.lne_domicilio_laboral_4.setText(_translate("Form_clientes_borrar", "Las violetas 45"))
        self.ckbx_recibo_sueldo_4.setText(_translate("Form_clientes_borrar", "Posee Recibo de Sueldo"))
        self.label_138.setText(_translate("Form_clientes_borrar", "Organismo: "))
        self.lne_organismo_4.setText(_translate("Form_clientes_borrar", "Ministerio de Educación"))
        self.label_141.setText(_translate("Form_clientes_borrar", "Antigüedad Laboral:"))
        self.label_142.setText(_translate("Form_clientes_borrar", "años"))
        self.label_139.setText(_translate("Form_clientes_borrar", "Ocupación:"))
        self.lne_ocupacion_4.setText(_translate("Form_clientes_borrar", "Auxiliar"))
        self.label_136.setText(_translate("Form_clientes_borrar", "Sueldo $:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), _translate("Form_clientes_borrar", "Datos laborales"))
        self.label_154.setText(_translate("Form_clientes_borrar", "Apellido:"))
        self.lne_garante_apellido_4.setText(_translate("Form_clientes_borrar", "Fernandez"))
        self.label_153.setText(_translate("Form_clientes_borrar", "Nombre :"))
        self.lne_garante_nombre_4.setText(_translate("Form_clientes_borrar", "Alejandro"))
        self.label_156.setText(_translate("Form_clientes_borrar", "N°  Cliente :"))
        self.lne_garante_nro_cliente_4.setText(_translate("Form_clientes_borrar", "00-001"))
        self.checkBox_10.setText(_translate("Form_clientes_borrar", "Activo"))
        self.label_150.setText(_translate("Form_clientes_borrar", "Tipo Documento:"))
        self.cbx_garante_tipo_doc_4.setItemText(0, _translate("Form_clientes_borrar", "DNI "))
        self.cbx_garante_tipo_doc_4.setItemText(1, _translate("Form_clientes_borrar", "CUIL"))
        self.cbx_garante_tipo_doc_4.setItemText(2, _translate("Form_clientes_borrar", "CUIT "))
        self.label_145.setText(_translate("Form_clientes_borrar", "Número:"))
        self.lne_garante_nro_doc_4.setText(_translate("Form_clientes_borrar", "5678879"))
        self.checkBox_11.setText(_translate("Form_clientes_borrar", "Inactivo"))
        self.label_148.setText(_translate("Form_clientes_borrar", "Fecha de Nacimiento:"))
        self.dte_garante_nacimiento_4.setDisplayFormat(_translate("Form_clientes_borrar", "yyyy/M/dd"))
        self.label_152.setText(_translate("Form_clientes_borrar", "Ciudad:"))
        self.cbx_garante_ciudad_4.setItemText(0, _translate("Form_clientes_borrar", "Viedma"))
        self.label_157.setText(_translate("Form_clientes_borrar", "Domicilio :"))
        self.lne_garante_domicilio_4.setText(_translate("Form_clientes_borrar", "Las violestas 68"))
        self.label_151.setText(_translate("Form_clientes_borrar", "Barrio:"))
        self.lne_garante_barrio_4.setText(_translate("Form_clientes_borrar", "Las flores"))
        self.label_146.setText(_translate("Form_clientes_borrar", "Teléfono:"))
        self.lne__garante_telefono_4.setText(_translate("Form_clientes_borrar", "2920-000001"))
        self.label_147.setText(_translate("Form_clientes_borrar", "Email:"))
        self.lne_garante_email_4.setText(_translate("Form_clientes_borrar", "email@email.com"))
        self.label_149.setText(_translate("Form_clientes_borrar", "Límite por Créditos:"))
        self.lne_garante_limite_credito_4.setText(_translate("Form_clientes_borrar", "10000"))
        self.label_155.setText(_translate("Form_clientes_borrar", "Estado Civil:"))
        self.cbx_garante_estado_civil_4.setItemText(0, _translate("Form_clientes_borrar", "Soltero/era"))
        self.cbx_garante_estado_civil_4.setItemText(1, _translate("Form_clientes_borrar", "Casado/ada"))
        self.cbx_garante_estado_civil_4.setItemText(2, _translate("Form_clientes_borrar", "Viudo/da"))
        self.cbx_garante_estado_civil_4.setItemText(3, _translate("Form_clientes_borrar", "Divorsiado/ada"))
        self.label_144.setText(_translate("Form_clientes_borrar", "Observaciones: "))
        self.boton_agregar_4.setText(_translate("Form_clientes_borrar", "Agregar"))
        item = self.tw_garantes_lista_4.verticalHeaderItem(0)
        item.setText(_translate("Form_clientes_borrar", "Garante Princ."))
        item = self.tw_garantes_lista_4.verticalHeaderItem(1)
        item.setText(_translate("Form_clientes_borrar", "Garante Sec."))
        item = self.tw_garantes_lista_4.verticalHeaderItem(2)
        item.setText(_translate("Form_clientes_borrar", "Otro Garante"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(0)
        item.setText(_translate("Form_clientes_borrar", "Apellido"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(1)
        item.setText(_translate("Form_clientes_borrar", "Nombre"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(2)
        item.setText(_translate("Form_clientes_borrar", "Nro. Cliente"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(3)
        item.setText(_translate("Form_clientes_borrar", "Tipo Doc."))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(4)
        item.setText(_translate("Form_clientes_borrar", "Número"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(5)
        item.setText(_translate("Form_clientes_borrar", "F. Nacimiento"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(6)
        item.setText(_translate("Form_clientes_borrar", "Ciudad"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(7)
        item.setText(_translate("Form_clientes_borrar", "Domicilio"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(8)
        item.setText(_translate("Form_clientes_borrar", "Teléfono"))
        item = self.tw_garantes_lista_4.horizontalHeaderItem(9)
        item.setText(_translate("Form_clientes_borrar", "Estado"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_18), _translate("Form_clientes_borrar", "Datos Garante"))
        self.label_161.setText(_translate("Form_clientes_borrar", "Tipo IVA:"))
        self.lne_iva_4.setText(_translate("Form_clientes_borrar", "Responsable Inscripto"))
        self.rbt_monotributista_4.setText(_translate("Form_clientes_borrar", "Monotributista"))
        self.label_158.setText(_translate("Form_clientes_borrar", "N° CUIT:"))
        self.lne_cuit_4.setText(_translate("Form_clientes_borrar", "00-5678879-00"))
        self.ckbx_facturas_4.setText(_translate("Form_clientes_borrar", "Presentó Facturas de Luz, Gas"))
        self.label_159.setText(_translate("Form_clientes_borrar", "N° CBU:"))
        self.lne_cbu_4.setText(_translate("Form_clientes_borrar", "00451597859478396574780"))
        self.ckbx_veraz_4.setText(_translate("Form_clientes_borrar", "Figura en el Veraz"))
        self.label_160.setText(_translate("Form_clientes_borrar", "N° Beneficio:"))
        self.lne_nro_beneficio_4.setText(_translate("Form_clientes_borrar", "00345687"))
        self.ckbx_jub_pens_4.setText(_translate("Form_clientes_borrar", "Es Jubilado / Pensionado"))
        self.ckbx_bloqueado_4.setText(_translate("Form_clientes_borrar", "Cliente Bloqueado"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_19), _translate("Form_clientes_borrar", "Otros Datos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_clientes_borrar", "Borrar Cliente"))
        self.pushButton_3.setText(_translate("Form_clientes_borrar", "Borrar"))
        self.pushButton_2.setText(_translate("Form_clientes_borrar", "Limpiar"))

