# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_credito_calcular.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_credito_calcular(object):
    def setupUi(self, form_credito_calcular):
        form_credito_calcular.setObjectName("form_credito_calcular")
        form_credito_calcular.resize(800, 490)
        form_credito_calcular.setMinimumSize(QtCore.QSize(800, 450))
        form_credito_calcular.setMaximumSize(QtCore.QSize(1600, 900))
        form_credito_calcular.setStyleSheet("font: 75 10pt \"KacstOne\";\n"
"selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(81, 1, 1);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(form_credito_calcular)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(form_credito_calcular)
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgba(136, 3, 3);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(20, 80, 125, 22))
        self.label_29.setMinimumSize(QtCore.QSize(125, 22))
        self.label_29.setMaximumSize(QtCore.QSize(125, 22))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(20, 110, 125, 22))
        self.label_30.setMinimumSize(QtCore.QSize(125, 22))
        self.label_30.setMaximumSize(QtCore.QSize(125, 22))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(20, 140, 125, 22))
        self.label_31.setMinimumSize(QtCore.QSize(125, 22))
        self.label_31.setMaximumSize(QtCore.QSize(125, 22))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(20, 170, 125, 22))
        self.label_32.setMinimumSize(QtCore.QSize(125, 22))
        self.label_32.setMaximumSize(QtCore.QSize(125, 22))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(20, 200, 125, 22))
        self.label_33.setMinimumSize(QtCore.QSize(125, 22))
        self.label_33.setMaximumSize(QtCore.QSize(125, 22))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(20, 230, 125, 22))
        self.label_34.setMinimumSize(QtCore.QSize(125, 22))
        self.label_34.setMaximumSize(QtCore.QSize(125, 22))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(20, 260, 125, 22))
        self.label_35.setMinimumSize(QtCore.QSize(125, 22))
        self.label_35.setMaximumSize(QtCore.QSize(125, 22))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(20, 290, 125, 22))
        self.label_36.setMinimumSize(QtCore.QSize(125, 22))
        self.label_36.setMaximumSize(QtCore.QSize(125, 22))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(20, 320, 125, 22))
        self.label_37.setMinimumSize(QtCore.QSize(125, 22))
        self.label_37.setMaximumSize(QtCore.QSize(125, 22))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(20, 360, 125, 22))
        self.label_38.setMinimumSize(QtCore.QSize(125, 22))
        self.label_38.setMaximumSize(QtCore.QSize(125, 22))
        self.label_38.setObjectName("label_38")
        self.lne_cta_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_3.setGeometry(QtCore.QRect(120, 80, 100, 25))
        self.lne_cta_3.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_3.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_3.setObjectName("lne_cta_3")
        self.lne_cta_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_4.setGeometry(QtCore.QRect(120, 110, 100, 25))
        self.lne_cta_4.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_4.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_4.setObjectName("lne_cta_4")
        self.lne_cta_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_5.setGeometry(QtCore.QRect(120, 140, 100, 25))
        self.lne_cta_5.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_5.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_5.setObjectName("lne_cta_5")
        self.lne_cta_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_6.setGeometry(QtCore.QRect(120, 170, 100, 25))
        self.lne_cta_6.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_6.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_6.setObjectName("lne_cta_6")
        self.lne_cta_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_7.setGeometry(QtCore.QRect(120, 200, 100, 25))
        self.lne_cta_7.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_7.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_7.setObjectName("lne_cta_7")
        self.lne_cta_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_8.setGeometry(QtCore.QRect(120, 230, 100, 25))
        self.lne_cta_8.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_8.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_8.setObjectName("lne_cta_8")
        self.lne_cta_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_9.setGeometry(QtCore.QRect(120, 260, 100, 25))
        self.lne_cta_9.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_9.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_9.setObjectName("lne_cta_9")
        self.lne_cta_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_10.setGeometry(QtCore.QRect(120, 290, 100, 25))
        self.lne_cta_10.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_10.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_10.setObjectName("lne_cta_10")
        self.lne_cta_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_11.setGeometry(QtCore.QRect(120, 320, 100, 25))
        self.lne_cta_11.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_11.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_11.setObjectName("lne_cta_11")
        self.lne_cta_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_12.setGeometry(QtCore.QRect(120, 360, 100, 25))
        self.lne_cta_12.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_12.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_12.setObjectName("lne_cta_12")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(480, 12, 125, 22))
        self.label.setMinimumSize(QtCore.QSize(125, 22))
        self.label.setMaximumSize(QtCore.QSize(125, 22))
        self.label.setObjectName("label")
        self.lne_cta_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_13.setGeometry(QtCore.QRect(611, 11, 100, 25))
        self.lne_cta_13.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_13.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_13.setObjectName("lne_cta_13")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(20, 10, 75, 25))
        self.label_25.setMinimumSize(QtCore.QSize(75, 25))
        self.label_25.setMaximumSize(QtCore.QSize(52, 25))
        self.label_25.setObjectName("label_25")
        self.lne_capital = QtWidgets.QLineEdit(self.tab_2)
        self.lne_capital.setGeometry(QtCore.QRect(20, 30, 100, 25))
        self.lne_capital.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_capital.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_capital.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_capital.setObjectName("lne_capital")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(480, 107, 125, 22))
        self.label_3.setMinimumSize(QtCore.QSize(125, 22))
        self.label_3.setMaximumSize(QtCore.QSize(125, 22))
        self.label_3.setObjectName("label_3")
        self.lne_cta_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_16.setGeometry(QtCore.QRect(611, 106, 100, 25))
        self.lne_cta_16.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_16.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_16.setObjectName("lne_cta_16")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(480, 75, 125, 22))
        self.label_7.setMinimumSize(QtCore.QSize(125, 22))
        self.label_7.setMaximumSize(QtCore.QSize(125, 22))
        self.label_7.setObjectName("label_7")
        self.lne_cta_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_15.setGeometry(QtCore.QRect(611, 74, 100, 25))
        self.lne_cta_15.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_15.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_15.setObjectName("lne_cta_15")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(480, 44, 125, 22))
        self.label_2.setMinimumSize(QtCore.QSize(125, 22))
        self.label_2.setMaximumSize(QtCore.QSize(125, 22))
        self.label_2.setObjectName("label_2")
        self.lne_cta_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_14.setGeometry(QtCore.QRect(611, 43, 100, 25))
        self.lne_cta_14.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_14.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_14.setObjectName("lne_cta_14")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(480, 138, 125, 22))
        self.label_6.setMinimumSize(QtCore.QSize(125, 22))
        self.label_6.setMaximumSize(QtCore.QSize(125, 22))
        self.label_6.setObjectName("label_6")
        self.lne_cta_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_17.setGeometry(QtCore.QRect(611, 137, 100, 25))
        self.lne_cta_17.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_17.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_17.setObjectName("lne_cta_17")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(480, 170, 125, 22))
        self.label_5.setMinimumSize(QtCore.QSize(125, 22))
        self.label_5.setMaximumSize(QtCore.QSize(125, 22))
        self.label_5.setObjectName("label_5")
        self.lne_cta_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_18.setGeometry(QtCore.QRect(611, 169, 100, 25))
        self.lne_cta_18.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_18.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_18.setObjectName("lne_cta_18")
        self.boton_calcular = QtWidgets.QPushButton(self.tab_2)
        self.boton_calcular.setGeometry(QtCore.QRect(170, 30, 100, 25))
        self.boton_calcular.setMinimumSize(QtCore.QSize(100, 25))
        self.boton_calcular.setMaximumSize(QtCore.QSize(100, 25))
        self.boton_calcular.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_calcular.setObjectName("boton_calcular")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(480, 201, 125, 22))
        self.label_4.setMinimumSize(QtCore.QSize(125, 22))
        self.label_4.setMaximumSize(QtCore.QSize(125, 22))
        self.label_4.setObjectName("label_4")
        self.lne_cta_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_19.setGeometry(QtCore.QRect(611, 200, 100, 25))
        self.lne_cta_19.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_19.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_19.setObjectName("lne_cta_19")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(480, 233, 125, 22))
        self.label_8.setMinimumSize(QtCore.QSize(125, 22))
        self.label_8.setMaximumSize(QtCore.QSize(125, 22))
        self.label_8.setObjectName("label_8")
        self.lne_cta_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_20.setGeometry(QtCore.QRect(611, 232, 100, 25))
        self.lne_cta_20.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_20.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_20.setObjectName("lne_cta_20")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(480, 264, 125, 22))
        self.label_9.setMinimumSize(QtCore.QSize(125, 22))
        self.label_9.setMaximumSize(QtCore.QSize(125, 22))
        self.label_9.setObjectName("label_9")
        self.lne_cta_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_21.setGeometry(QtCore.QRect(611, 263, 100, 25))
        self.lne_cta_21.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_21.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_21.setObjectName("lne_cta_21")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(480, 296, 125, 22))
        self.label_10.setMinimumSize(QtCore.QSize(125, 22))
        self.label_10.setMaximumSize(QtCore.QSize(125, 22))
        self.label_10.setObjectName("label_10")
        self.lne_cta_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_22.setGeometry(QtCore.QRect(611, 295, 100, 25))
        self.lne_cta_22.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_22.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_22.setObjectName("lne_cta_22")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(480, 327, 125, 22))
        self.label_11.setMinimumSize(QtCore.QSize(125, 22))
        self.label_11.setMaximumSize(QtCore.QSize(125, 22))
        self.label_11.setObjectName("label_11")
        self.lne_cta_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_23.setGeometry(QtCore.QRect(611, 326, 100, 25))
        self.lne_cta_23.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_23.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_23.setObjectName("lne_cta_23")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(480, 359, 125, 22))
        self.label_12.setMinimumSize(QtCore.QSize(125, 22))
        self.label_12.setMaximumSize(QtCore.QSize(125, 22))
        self.label_12.setObjectName("label_12")
        self.lne_cta_24 = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cta_24.setGeometry(QtCore.QRect(611, 358, 100, 25))
        self.lne_cta_24.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_cta_24.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_cta_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cta_24.setObjectName("lne_cta_24")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/calculadora.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_2, icon, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, icon, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(form_credito_calcular)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_credito_calcular)

    def retranslateUi(self, form_credito_calcular):
        _translate = QtCore.QCoreApplication.translate
        form_credito_calcular.setWindowTitle(_translate("form_credito_calcular", "Calcular Crédito"))
        self.label_29.setText(_translate("form_credito_calcular", "3 Cuotas de $"))
        self.label_30.setText(_translate("form_credito_calcular", "4 Cuotas de $"))
        self.label_31.setText(_translate("form_credito_calcular", "5 Cuotas de $"))
        self.label_32.setText(_translate("form_credito_calcular", "6 Cuotas de $"))
        self.label_33.setText(_translate("form_credito_calcular", "7 Cuotas de $"))
        self.label_34.setText(_translate("form_credito_calcular", "8 Cuotas de $"))
        self.label_35.setText(_translate("form_credito_calcular", "9 Cuotas de $"))
        self.label_36.setText(_translate("form_credito_calcular", "10 Cuotas de $"))
        self.label_37.setText(_translate("form_credito_calcular", "11 Cuotas de $"))
        self.label_38.setText(_translate("form_credito_calcular", "12 Cuotas de $"))
        self.label.setText(_translate("form_credito_calcular", "13 Cuotas de $"))
        self.label_25.setText(_translate("form_credito_calcular", "Capital:"))
        self.label_3.setText(_translate("form_credito_calcular", "16 Cuotas de $"))
        self.label_7.setText(_translate("form_credito_calcular", "15 Cuotas de $"))
        self.label_2.setText(_translate("form_credito_calcular", "14 Cuotas de $"))
        self.label_6.setText(_translate("form_credito_calcular", "17 Cuotas de $"))
        self.label_5.setText(_translate("form_credito_calcular", "18 Cuotas de $"))
        self.boton_calcular.setText(_translate("form_credito_calcular", "Calcular"))
        self.label_4.setText(_translate("form_credito_calcular", "19 Cuotas de $"))
        self.label_8.setText(_translate("form_credito_calcular", "20 Cuotas de $"))
        self.label_9.setText(_translate("form_credito_calcular", "21 Cuotas de $"))
        self.label_10.setText(_translate("form_credito_calcular", "22 Cuotas de $"))
        self.label_11.setText(_translate("form_credito_calcular", "23 Cuotas de $"))
        self.label_12.setText(_translate("form_credito_calcular", "24 Cuotas de $"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("form_credito_calcular", "Calcular"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_credito_calcular", "Cálculo de Crédito"))

