# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_cobradores_registrar.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_registrar_cobradores(object):
    def setupUi(self, form_registrar_cobradores):
        form_registrar_cobradores.setObjectName("form_registrar_cobradores")
        form_registrar_cobradores.resize(1020, 720)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        form_registrar_cobradores.setPalette(palette)
        self.groupBox = QtWidgets.QGroupBox(form_registrar_cobradores)
        self.groupBox.setGeometry(QtCore.QRect(40, 10, 571, 211))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 550, 161))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 190, 551, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(form_registrar_cobradores)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 230, 571, 311))
        self.groupBox_2.setAcceptDrops(False)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lne_nombre = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_nombre.setGeometry(QtCore.QRect(100, 40, 300, 20))
        self.lne_nombre.setObjectName("lne_nombre")
        self.cbx_cobra_predeterminado = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbx_cobra_predeterminado.setGeometry(QtCore.QRect(20, 270, 181, 21))
        self.cbx_cobra_predeterminado.setChecked(True)
        self.cbx_cobra_predeterminado.setObjectName("cbx_cobra_predeterminado")
        self.cbx_cobra_activo = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbx_cobra_activo.setGeometry(QtCore.QRect(20, 290, 181, 21))
        self.cbx_cobra_activo.setObjectName("cbx_cobra_activo")
        self.lne_apellido = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_apellido.setGeometry(QtCore.QRect(100, 70, 300, 20))
        self.lne_apellido.setObjectName("lne_apellido")
        self.lne_documento = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_documento.setGeometry(QtCore.QRect(100, 100, 300, 20))
        self.lne_documento.setObjectName("lne_documento")
        self.lne_domicilio = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_domicilio.setGeometry(QtCore.QRect(100, 130, 300, 20))
        self.lne_domicilio.setObjectName("lne_domicilio")
        self.lne_telefono = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_telefono.setGeometry(QtCore.QRect(100, 160, 300, 20))
        self.lne_telefono.setObjectName("lne_telefono")
        self.lne_importe_peso = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_importe_peso.setGeometry(QtCore.QRect(290, 220, 91, 20))
        self.lne_importe_peso.setObjectName("lne_importe_peso")
        self.lne_importeporcentaje = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_importeporcentaje.setGeometry(QtCore.QRect(290, 250, 91, 20))
        self.lne_importeporcentaje.setObjectName("lne_importeporcentaje")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(80, 220, 181, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(78, 248, 180, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(30, 190, 211, 17))
        self.label_9.setObjectName("label_9")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.lne_nombre.raise_()
        self.cbx_cobra_predeterminado.raise_()
        self.cbx_cobra_activo.raise_()
        self.lne_apellido.raise_()
        self.lne_documento.raise_()
        self.lne_domicilio.raise_()
        self.lne_telefono.raise_()
        self.lne_importe_peso.raise_()
        self.lne_importeporcentaje.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.btn_agregar = QtWidgets.QPushButton(form_registrar_cobradores)
        self.btn_agregar.setGeometry(QtCore.QRect(400, 550, 80, 23))
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_limpiar = QtWidgets.QPushButton(form_registrar_cobradores)
        self.btn_limpiar.setGeometry(QtCore.QRect(520, 550, 80, 23))
        self.btn_limpiar.setObjectName("btn_limpiar")

        self.retranslateUi(form_registrar_cobradores)
        self.btn_limpiar.clicked.connect(self.lne_nombre.clear)
        self.btn_limpiar.clicked.connect(self.lne_apellido.clear)
        self.btn_limpiar.clicked.connect(self.lne_documento.clear)
        self.btn_limpiar.clicked.connect(self.lne_domicilio.clear)
        self.btn_limpiar.clicked.connect(self.lne_telefono.clear)
        self.btn_limpiar.clicked.connect(self.lne_importe_peso.clear)
        self.btn_limpiar.clicked.connect(self.lne_importeporcentaje.clear)
        QtCore.QMetaObject.connectSlotsByName(form_registrar_cobradores)

    def retranslateUi(self, form_registrar_cobradores):
        _translate = QtCore.QCoreApplication.translate
        form_registrar_cobradores.setWindowTitle(_translate("form_registrar_cobradores", "Dialog"))
        self.groupBox.setTitle(_translate("form_registrar_cobradores", "Lista de cobradores"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("form_registrar_cobradores", "Cobrador"))
        self.label.setText(_translate("form_registrar_cobradores", "Aqui se agregan los cobradores de cuotas a los cuales se les puede abonar una comision opcional."))
        self.groupBox_2.setTitle(_translate("form_registrar_cobradores", "Datos"))
        self.label_2.setText(_translate("form_registrar_cobradores", "Nombre:"))
        self.label_3.setText(_translate("form_registrar_cobradores", "Apellido:"))
        self.label_4.setText(_translate("form_registrar_cobradores", "Documento:"))
        self.label_5.setText(_translate("form_registrar_cobradores", "Domicilio:"))
        self.label_6.setText(_translate("form_registrar_cobradores", "Teléfono:"))
        self.lne_nombre.setText(_translate("form_registrar_cobradores", "Fernandez"))
        self.cbx_cobra_predeterminado.setText(_translate("form_registrar_cobradores", "Cobrador predeterminado"))
        self.cbx_cobra_activo.setText(_translate("form_registrar_cobradores", "Cobrador activo"))
        self.lne_apellido.setText(_translate("form_registrar_cobradores", "Violeta"))
        self.lne_documento.setText(_translate("form_registrar_cobradores", "12435678"))
        self.lne_domicilio.setText(_translate("form_registrar_cobradores", "las violetas 69"))
        self.lne_telefono.setText(_translate("form_registrar_cobradores", "2920-007865"))
        self.lne_importe_peso.setText(_translate("form_registrar_cobradores", "2920-007865"))
        self.lne_importeporcentaje.setText(_translate("form_registrar_cobradores", "2920-007865"))
        self.label_7.setText(_translate("form_registrar_cobradores", "Aplicar importe de comision  $:"))
        self.label_8.setText(_translate("form_registrar_cobradores", "Aplicar importe de comision  %:"))
        self.label_9.setText(_translate("form_registrar_cobradores", "Aplicar comision por cobro de cuotas"))
        self.btn_agregar.setText(_translate("form_registrar_cobradores", "Agregar"))
        self.btn_limpiar.setText(_translate("form_registrar_cobradores", "Limpiar"))

