# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_creditos_refinanciar.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_creditos_refinanciar(object):
    def setupUi(self, form_creditos_refinanciar):
        form_creditos_refinanciar.setObjectName("form_creditos_refinanciar")
        form_creditos_refinanciar.resize(1400, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(form_creditos_refinanciar.sizePolicy().hasHeightForWidth())
        form_creditos_refinanciar.setSizePolicy(sizePolicy)
        form_creditos_refinanciar.setMinimumSize(QtCore.QSize(800, 450))
        form_creditos_refinanciar.setMaximumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        form_creditos_refinanciar.setFont(font)
        form_creditos_refinanciar.setStyleSheet("font: 75 10pt \"KacstOne\";\n"
"selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(81, 1, 1);\n"
"selection-color: rgb(0, 0, 0);")
        self.tabWidget_4 = QtWidgets.QTabWidget(form_creditos_refinanciar)
        self.tabWidget_4.setGeometry(QtCore.QRect(20, 340, 961, 391))
        self.tabWidget_4.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-color: rgb(172, 55, 26);\n"
"border-radius: 8px;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tw_listado_cuotas = QtWidgets.QTableWidget(self.groupBox_3)
        self.tw_listado_cuotas.setEnabled(False)
        self.tw_listado_cuotas.setStyleSheet("background-color: rgb(252, 188, 188);")
        self.tw_listado_cuotas.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tw_listado_cuotas.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tw_listado_cuotas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_listado_cuotas.setObjectName("tw_listado_cuotas")
        self.tw_listado_cuotas.setColumnCount(15)
        self.tw_listado_cuotas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listado_cuotas.setHorizontalHeaderItem(14, item)
        self.tw_listado_cuotas.horizontalHeader().setDefaultSectionSize(100)
        self.gridLayout_3.addWidget(self.tw_listado_cuotas, 3, 0, 1, 1)
        self.boton_historial_cuota = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_historial_cuota.setMinimumSize(QtCore.QSize(0, 25))
        self.boton_historial_cuota.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_historial_cuota.setStyleSheet("background-color: rgb(252, 188, 188);")
        self.boton_historial_cuota.setObjectName("boton_historial_cuota")
        self.gridLayout_3.addWidget(self.boton_historial_cuota, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/herramientas-de-papel-y-lapiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.tab_3, icon, "")
        self.tabWidget_5 = QtWidgets.QTabWidget(form_creditos_refinanciar)
        self.tabWidget_5.setGeometry(QtCore.QRect(990, 50, 321, 281))
        self.tabWidget_5.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setMinimumSize(QtCore.QSize(300, 20))
        self.label_3.setMaximumSize(QtCore.QSize(300, 20))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-color: rgb(172, 55, 26);\n"
"border-radius: 8px;\n"
"font:  75 10Pt \"Century Schoolbook L\";\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.boton_agregar = QtWidgets.QPushButton(self.groupBox_4)
        self.boton_agregar.setGeometry(QtCore.QRect(70, 130, 141, 23))
        self.boton_agregar.setObjectName("boton_agregar")
        self.cant_cuotas = QtWidgets.QSpinBox(self.groupBox_4)
        self.cant_cuotas.setGeometry(QtCore.QRect(185, 33, 38, 22))
        self.cant_cuotas.setObjectName("cant_cuotas")
        self.dte_primer_venc = QtWidgets.QDateEdit(self.groupBox_4)
        self.dte_primer_venc.setGeometry(QtCore.QRect(185, 89, 68, 22))
        self.dte_primer_venc.setObjectName("dte_primer_venc")
        self.lne_monto = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_monto.setGeometry(QtCore.QRect(185, 60, 81, 24))
        self.lne_monto.setObjectName("lne_monto")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(45, 38, 130, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(130, 60, 45, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(12, 90, 165, 16))
        self.label_5.setObjectName("label_5")
        self.boton_imprimir = QtWidgets.QPushButton(self.groupBox_4)
        self.boton_imprimir.setGeometry(QtCore.QRect(100, 160, 80, 21))
        self.boton_imprimir.setObjectName("boton_imprimir")
        self.gridLayout_8.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_8.addWidget(self.line_2, 3, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/maquina-de-facturacion-electronica-con-escaner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_5.addTab(self.tab_5, icon1, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(form_creditos_refinanciar)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 80, 961, 241))
        self.tabWidget_3.setStyleSheet("background-color: rgb(252, 249, 247);")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-color: rgb(172, 55, 26);\n"
"border-radius: 8px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_lista_creditos = QtWidgets.QTableWidget(self.groupBox_2)
        self.tw_lista_creditos.setEnabled(False)
        self.tw_lista_creditos.setStyleSheet("background-color: rgb(252, 188, 188);")
        self.tw_lista_creditos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tw_lista_creditos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_lista_creditos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tw_lista_creditos.setObjectName("tw_lista_creditos")
        self.tw_lista_creditos.setColumnCount(10)
        self.tw_lista_creditos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_lista_creditos.setHorizontalHeaderItem(9, item)
        self.tw_lista_creditos.horizontalHeader().setDefaultSectionSize(125)
        self.gridLayout.addWidget(self.tw_lista_creditos, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Íconos/documento-financiero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_4, icon2, "")
        self.layoutWidget = QtWidgets.QWidget(form_creditos_refinanciar)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 120, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lne_capital = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_capital.setEnabled(False)
        self.lne_capital.setMinimumSize(QtCore.QSize(20, 20))
        self.lne_capital.setMaximumSize(QtCore.QSize(2, 20))
        self.lne_capital.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_capital.setObjectName("lne_capital")
        self.horizontalLayout_2.addWidget(self.lne_capital)
        self.lne_interes = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_interes.setEnabled(False)
        self.lne_interes.setMinimumSize(QtCore.QSize(20, 20))
        self.lne_interes.setMaximumSize(QtCore.QSize(20, 20))
        self.lne_interes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_interes.setObjectName("lne_interes")
        self.horizontalLayout_2.addWidget(self.lne_interes)
        self.lne_gastos = QtWidgets.QLineEdit(self.layoutWidget)
        self.lne_gastos.setEnabled(False)
        self.lne_gastos.setMinimumSize(QtCore.QSize(20, 20))
        self.lne_gastos.setMaximumSize(QtCore.QSize(20, 20))
        self.lne_gastos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_gastos.setObjectName("lne_gastos")
        self.horizontalLayout_2.addWidget(self.lne_gastos)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(form_creditos_refinanciar)
        self.label.setGeometry(QtCore.QRect(780, 10, 29, 16))
        self.label.setObjectName("label")
        self.lne_dni = QtWidgets.QLineEdit(form_creditos_refinanciar)
        self.lne_dni.setGeometry(QtCore.QRect(830, 10, 125, 24))
        self.lne_dni.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lne_dni.setObjectName("lne_dni")
        self.boton_buscar_creditos = QtWidgets.QPushButton(form_creditos_refinanciar)
        self.boton_buscar_creditos.setGeometry(QtCore.QRect(970, 10, 80, 23))
        self.boton_buscar_creditos.setStyleSheet("background-color: rgb(252, 188, 188);")
        self.boton_buscar_creditos.setObjectName("boton_buscar_creditos")
        self.lne_nom_ape = QtWidgets.QLineEdit(form_creditos_refinanciar)
        self.lne_nom_ape.setGeometry(QtCore.QRect(40, 10, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lne_nom_ape.setFont(font)
        self.lne_nom_ape.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Ubuntu\";\n"
"")
        self.lne_nom_ape.setText("")
        self.lne_nom_ape.setObjectName("lne_nom_ape")
        self.label.raise_()
        self.lne_dni.raise_()
        self.boton_buscar_creditos.raise_()
        self.lne_nom_ape.raise_()
        self.layoutWidget.raise_()
        self.tabWidget_4.raise_()
        self.tabWidget_5.raise_()
        self.tabWidget_3.raise_()

        self.retranslateUi(form_creditos_refinanciar)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_creditos_refinanciar)
        form_creditos_refinanciar.setTabOrder(self.lne_dni, self.boton_buscar_creditos)
        form_creditos_refinanciar.setTabOrder(self.boton_buscar_creditos, self.lne_nom_ape)
        form_creditos_refinanciar.setTabOrder(self.lne_nom_ape, self.tabWidget_3)
        form_creditos_refinanciar.setTabOrder(self.tabWidget_3, self.tw_lista_creditos)
        form_creditos_refinanciar.setTabOrder(self.tw_lista_creditos, self.lne_capital)
        form_creditos_refinanciar.setTabOrder(self.lne_capital, self.tabWidget_4)
        form_creditos_refinanciar.setTabOrder(self.tabWidget_4, self.tw_listado_cuotas)
        form_creditos_refinanciar.setTabOrder(self.tw_listado_cuotas, self.tabWidget_5)

    def retranslateUi(self, form_creditos_refinanciar):
        _translate = QtCore.QCoreApplication.translate
        form_creditos_refinanciar.setWindowTitle(_translate("form_creditos_refinanciar", "Cuotas Pagar"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(0)
        item.setText(_translate("form_creditos_refinanciar", "Estado"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(1)
        item.setText(_translate("form_creditos_refinanciar", "N° Cuota"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(2)
        item.setText(_translate("form_creditos_refinanciar", "Vencimiento"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(3)
        item.setText(_translate("form_creditos_refinanciar", "Importe Cuota"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(4)
        item.setText(_translate("form_creditos_refinanciar", "Punitorio"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(5)
        item.setText(_translate("form_creditos_refinanciar", "Descuento"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(6)
        item.setText(_translate("form_creditos_refinanciar", "Cuota pagar"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(7)
        item.setText(_translate("form_creditos_refinanciar", "Importe Cobrado"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(8)
        item.setText(_translate("form_creditos_refinanciar", "Saldo"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(9)
        item.setText(_translate("form_creditos_refinanciar", "Fecha de Cobro"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(10)
        item.setText(_translate("form_creditos_refinanciar", "Capital"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(11)
        item.setText(_translate("form_creditos_refinanciar", "Interes"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(12)
        item.setText(_translate("form_creditos_refinanciar", "Gastos"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(13)
        item.setText(_translate("form_creditos_refinanciar", "Descripcion"))
        item = self.tw_listado_cuotas.horizontalHeaderItem(14)
        item.setText(_translate("form_creditos_refinanciar", "id"))
        self.boton_historial_cuota.setText(_translate("form_creditos_refinanciar", "Historial de Cuota"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_3), _translate("form_creditos_refinanciar", "Cuotas del Crédito"))
        self.label_3.setText(_translate("form_creditos_refinanciar", "Información a editar por el Usuario : "))
        self.boton_agregar.setText(_translate("form_creditos_refinanciar", "Refinanciar"))
        self.label_2.setText(_translate("form_creditos_refinanciar", "Cantiodad de cuotas :"))
        self.label_4.setText(_translate("form_creditos_refinanciar", "Monto :"))
        self.label_5.setText(_translate("form_creditos_refinanciar", "Fecha primer Vencimiento :"))
        self.boton_imprimir.setText(_translate("form_creditos_refinanciar", "Imprimir"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_5), _translate("form_creditos_refinanciar", "Pago de Cuota"))
        item = self.tw_lista_creditos.horizontalHeaderItem(0)
        item.setText(_translate("form_creditos_refinanciar", "Crédito N°"))
        item = self.tw_lista_creditos.horizontalHeaderItem(1)
        item.setText(_translate("form_creditos_refinanciar", "Cliente"))
        item = self.tw_lista_creditos.horizontalHeaderItem(2)
        item.setText(_translate("form_creditos_refinanciar", "Fecha Crédito"))
        item = self.tw_lista_creditos.horizontalHeaderItem(3)
        item.setText(_translate("form_creditos_refinanciar", "N° Cuotas"))
        item = self.tw_lista_creditos.horizontalHeaderItem(4)
        item.setText(_translate("form_creditos_refinanciar", "Capital"))
        item = self.tw_lista_creditos.horizontalHeaderItem(5)
        item.setText(_translate("form_creditos_refinanciar", "Finalizado"))
        item = self.tw_lista_creditos.horizontalHeaderItem(6)
        item.setText(_translate("form_creditos_refinanciar", "Bloqueado"))
        item = self.tw_lista_creditos.horizontalHeaderItem(7)
        item.setText(_translate("form_creditos_refinanciar", "Formula"))
        item = self.tw_lista_creditos.horizontalHeaderItem(8)
        item.setText(_translate("form_creditos_refinanciar", "Tipo Vencimiento"))
        item = self.tw_lista_creditos.horizontalHeaderItem(9)
        item.setText(_translate("form_creditos_refinanciar", "Observaciones"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("form_creditos_refinanciar", "Historial de Cŕeditos"))
        self.label.setText(_translate("form_creditos_refinanciar", "DNI: "))
        self.boton_buscar_creditos.setText(_translate("form_creditos_refinanciar", "Buscar"))

