# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_cuota_reparar.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_reparar_cuota(object):
    def setupUi(self, Form_reparar_cuota):
        Form_reparar_cuota.setObjectName("Form_reparar_cuota")
        Form_reparar_cuota.resize(640, 536)
        Form_reparar_cuota.setStyleSheet("font: 75 10pt \"KacstOne\";\n"
"selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(81, 1, 1);\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form_reparar_cuota)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form_reparar_cuota)
        self.tabWidget.setStyleSheet("background-color: rgba(136, 3, 3);\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.lne_num_credito = QtWidgets.QLineEdit(self.tab)
        self.lne_num_credito.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_num_credito.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_num_credito.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lne_num_credito.setObjectName("lne_num_credito")
        self.horizontalLayout_8.addWidget(self.lne_num_credito)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lne_num_cuota = QtWidgets.QLineEdit(self.tab)
        self.lne_num_cuota.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_num_cuota.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_num_cuota.setStyleSheet("background-color: rgb(239, 235, 231);")
        self.lne_num_cuota.setObjectName("lne_num_cuota")
        self.horizontalLayout_8.addWidget(self.lne_num_cuota)
        self.boton_buscar = QtWidgets.QPushButton(self.tab)
        self.boton_buscar.setMinimumSize(QtCore.QSize(0, 25))
        self.boton_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_buscar.setStyleSheet("background-color: rgb(219, 106, 80);")
        self.boton_buscar.setObjectName("boton_buscar")
        self.horizontalLayout_8.addWidget(self.boton_buscar)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lne_id_cuota_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_id_cuota_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_id_cuota_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_id_cuota_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_id_cuota_reparar.setObjectName("lne_id_cuota_reparar")
        self.horizontalLayout.addWidget(self.lne_id_cuota_reparar)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.lne_cobrado_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_cobrado_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_cobrado_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_cobrado_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cobrado_reparar.setObjectName("lne_cobrado_reparar")
        self.horizontalLayout.addWidget(self.lne_cobrado_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lne_nro_cuota_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_nro_cuota_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_nro_cuota_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_nro_cuota_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_cuota_reparar.setObjectName("lne_nro_cuota_reparar")
        self.horizontalLayout_2.addWidget(self.lne_nro_cuota_reparar)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lne_interes_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_interes_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_interes_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_interes_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_interes_reparar.setObjectName("lne_interes_reparar")
        self.horizontalLayout_2.addWidget(self.lne_interes_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.cbx_estado = QtWidgets.QComboBox(self.tab_2)
        self.cbx_estado.setEnabled(True)
        self.cbx_estado.setMinimumSize(QtCore.QSize(0, 25))
        self.cbx_estado.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_estado.setStyleSheet("background-color: rgb(252, 188, 188);")
        self.cbx_estado.setObjectName("cbx_estado")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.horizontalLayout_3.addWidget(self.cbx_estado)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lne_gastos_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_gastos_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_gastos_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_gastos_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_gastos_reparar.setObjectName("lne_gastos_reparar")
        self.horizontalLayout_3.addWidget(self.lne_gastos_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.lne_venc_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_venc_reparar.setEnabled(False)
        self.lne_venc_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_venc_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_venc_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_venc_reparar.setObjectName("lne_venc_reparar")
        self.horizontalLayout_4.addWidget(self.lne_venc_reparar)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lne_capital_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_capital_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_capital_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_capital_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_capital_reparar.setObjectName("lne_capital_reparar")
        self.horizontalLayout_4.addWidget(self.lne_capital_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lne_importe_cuota_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_importe_cuota_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_importe_cuota_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_importe_cuota_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_importe_cuota_reparar.setObjectName("lne_importe_cuota_reparar")
        self.horizontalLayout_5.addWidget(self.lne_importe_cuota_reparar)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setMinimumSize(QtCore.QSize(0, 25))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.lne_punitorio_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_punitorio_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_punitorio_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_punitorio_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_punitorio_reparar.setObjectName("lne_punitorio_reparar")
        self.horizontalLayout_5.addWidget(self.lne_punitorio_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.dte_fecha_cobro = QtWidgets.QDateEdit(self.tab_2)
        self.dte_fecha_cobro.setMinimumSize(QtCore.QSize(0, 25))
        self.dte_fecha_cobro.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dte_fecha_cobro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fecha_cobro.setDate(QtCore.QDate(2017, 1, 1))
        self.dte_fecha_cobro.setObjectName("dte_fecha_cobro")
        self.horizontalLayout_6.addWidget(self.dte_fecha_cobro)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.lne_descuento_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_descuento_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_descuento_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_descuento_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_descuento_reparar.setObjectName("lne_descuento_reparar")
        self.horizontalLayout_6.addWidget(self.lne_descuento_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lne_descripcion_reparar = QtWidgets.QLineEdit(self.tab_2)
        self.lne_descripcion_reparar.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_descripcion_reparar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_descripcion_reparar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_descripcion_reparar.setObjectName("lne_descripcion_reparar")
        self.horizontalLayout_7.addWidget(self.lne_descripcion_reparar)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/icono-de-una-tuerca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.boton_actualizar = QtWidgets.QPushButton(Form_reparar_cuota)
        self.boton_actualizar.setMinimumSize(QtCore.QSize(0, 25))
        self.boton_actualizar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.boton_actualizar.setStyleSheet("background-color: rgb(172, 55, 26);")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.gridLayout_3.addWidget(self.boton_actualizar, 1, 0, 1, 1, QtCore.Qt.AlignRight)

        self.retranslateUi(Form_reparar_cuota)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_reparar_cuota)
        Form_reparar_cuota.setTabOrder(self.boton_actualizar, self.tabWidget)

    def retranslateUi(self, Form_reparar_cuota):
        _translate = QtCore.QCoreApplication.translate
        Form_reparar_cuota.setWindowTitle(_translate("Form_reparar_cuota", "Reparar Cuota"))
        self.label.setText(_translate("Form_reparar_cuota", "N° Crédito : "))
        self.label_2.setText(_translate("Form_reparar_cuota", "N° Cuota : "))
        self.boton_buscar.setText(_translate("Form_reparar_cuota", "Buscar"))
        self.label_9.setText(_translate("Form_reparar_cuota", "id:"))
        self.label_15.setText(_translate("Form_reparar_cuota", "Importe Cobrado: "))
        self.label_3.setText(_translate("Form_reparar_cuota", "N° Cuota: "))
        self.label_5.setText(_translate("Form_reparar_cuota", "Interés:"))
        self.label_13.setText(_translate("Form_reparar_cuota", "Estado: "))
        self.cbx_estado.setItemText(0, _translate("Form_reparar_cuota", "Pagada"))
        self.cbx_estado.setItemText(1, _translate("Form_reparar_cuota", "Pago Parcial"))
        self.cbx_estado.setItemText(2, _translate("Form_reparar_cuota", "A pagar"))
        self.cbx_estado.setItemText(3, _translate("Form_reparar_cuota", "Vencida 30 días"))
        self.cbx_estado.setItemText(4, _translate("Form_reparar_cuota", "Vencida 60 días"))
        self.cbx_estado.setItemText(5, _translate("Form_reparar_cuota", "Vencida 90 días"))
        self.cbx_estado.setItemText(6, _translate("Form_reparar_cuota", "Vencida 120 días"))
        self.cbx_estado.setItemText(7, _translate("Form_reparar_cuota", "Vencida 150 días"))
        self.cbx_estado.setItemText(8, _translate("Form_reparar_cuota", "Vencida 180 días"))
        self.cbx_estado.setItemText(9, _translate("Form_reparar_cuota", "En Judiciales"))
        self.label_6.setText(_translate("Form_reparar_cuota", "Gastos:"))
        self.label_12.setText(_translate("Form_reparar_cuota", "Vencimiento: "))
        self.label_4.setText(_translate("Form_reparar_cuota", "Capital:"))
        self.label_11.setText(_translate("Form_reparar_cuota", "Importe 1er Venc: "))
        self.label_16.setText(_translate("Form_reparar_cuota", "Punitorio: "))
        self.label_17.setText(_translate("Form_reparar_cuota", "Fecha de Cobro: "))
        self.dte_fecha_cobro.setDisplayFormat(_translate("Form_reparar_cuota", "dd/MM/yyyy"))
        self.label_18.setText(_translate("Form_reparar_cuota", "Descuento :"))
        self.label_8.setText(_translate("Form_reparar_cuota", "Descripción:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form_reparar_cuota", "Detalle de Cuota"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_reparar_cuota", "Reparar Cuota"))
        self.boton_actualizar.setText(_translate("Form_reparar_cuota", "Actualizar"))

