# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_clientes_actualizar.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_clientes_actualizar(object):
    def setupUi(self, Form_clientes_actualizar):
        Form_clientes_actualizar.setObjectName("Form_clientes_actualizar")
        Form_clientes_actualizar.resize(1600, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_clientes_actualizar.sizePolicy().hasHeightForWidth())
        Form_clientes_actualizar.setSizePolicy(sizePolicy)
        Form_clientes_actualizar.setMinimumSize(QtCore.QSize(800, 450))
        Form_clientes_actualizar.setMaximumSize(QtCore.QSize(1600, 850))
        Form_clientes_actualizar.setStyleSheet("font: 75 10pt \"KacstOne\";\n"
"selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(81, 1, 1);")
        self.gridLayout_8 = QtWidgets.QGridLayout(Form_clientes_actualizar)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Form_clientes_actualizar)
        self.tabWidget.setStyleSheet("background-color: rgba(136, 3, 3);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_122 = QtWidgets.QLabel(self.tab)
        self.label_122.setStyleSheet("font: 75 10pt \"KacstOne\";")
        self.label_122.setObjectName("label_122")
        self.horizontalLayout.addWidget(self.label_122)
        self.lne_dni_filtro_actualizar = QtWidgets.QLineEdit(self.tab)
        self.lne_dni_filtro_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_dni_filtro_actualizar.setText("")
        self.lne_dni_filtro_actualizar.setObjectName("lne_dni_filtro_actualizar")
        self.horizontalLayout.addWidget(self.lne_dni_filtro_actualizar)
        self.boton_buscar_actualizar = QtWidgets.QPushButton(self.tab)
        self.boton_buscar_actualizar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_buscar_actualizar.setObjectName("boton_buscar_actualizar")
        self.horizontalLayout.addWidget(self.boton_buscar_actualizar, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lne_id_party_actualizar = QtWidgets.QLineEdit(self.tab)
        self.lne_id_party_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_id_party_actualizar.setText("")
        self.lne_id_party_actualizar.setObjectName("lne_id_party_actualizar")
        self.horizontalLayout_2.addWidget(self.lne_id_party_actualizar)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.boton_limpiar_actualizar_cliente = QtWidgets.QPushButton(self.tab)
        self.boton_limpiar_actualizar_cliente.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"font: 75 10pt \"KacstOne\";")
        self.boton_limpiar_actualizar_cliente.setObjectName("boton_limpiar_actualizar_cliente")
        self.horizontalLayout_2.addWidget(self.boton_limpiar_actualizar_cliente)
        self.boton_actualizar = QtWidgets.QPushButton(self.tab)
        self.boton_actualizar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"font: 75 10pt \"KacstOne\";")
        self.boton_actualizar.setObjectName("boton_actualizar")
        self.horizontalLayout_2.addWidget(self.boton_actualizar, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.tab_widget_actualizar_cliente = QtWidgets.QTabWidget(self.tab)
        self.tab_widget_actualizar_cliente.setEnabled(False)
        self.tab_widget_actualizar_cliente.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tab_widget_actualizar_cliente.setObjectName("tab_widget_actualizar_cliente")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_134 = QtWidgets.QLabel(self.groupBox)
        self.label_134.setObjectName("label_134")
        self.horizontalLayout_3.addWidget(self.label_134)
        self.lne_apellido_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_apellido_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_apellido_actualizar.setText("")
        self.lne_apellido_actualizar.setObjectName("lne_apellido_actualizar")
        self.horizontalLayout_3.addWidget(self.lne_apellido_actualizar)
        self.label_125 = QtWidgets.QLabel(self.groupBox)
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_3.addWidget(self.label_125)
        self.lne_nombre_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nombre_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre_actualizar.setText("")
        self.lne_nombre_actualizar.setObjectName("lne_nombre_actualizar")
        self.horizontalLayout_3.addWidget(self.lne_nombre_actualizar)
        self.label_129 = QtWidgets.QLabel(self.groupBox)
        self.label_129.setObjectName("label_129")
        self.horizontalLayout_3.addWidget(self.label_129)
        self.lne_nro_cliente = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nro_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_cliente.setText("")
        self.lne_nro_cliente.setObjectName("lne_nro_cliente")
        self.horizontalLayout_3.addWidget(self.lne_nro_cliente)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_128 = QtWidgets.QLabel(self.groupBox)
        self.label_128.setObjectName("label_128")
        self.horizontalLayout_4.addWidget(self.label_128)
        self.cbx_tipo_doc_actualizar = QtWidgets.QComboBox(self.groupBox)
        self.cbx_tipo_doc_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_tipo_doc_actualizar.setObjectName("cbx_tipo_doc_actualizar")
        self.cbx_tipo_doc_actualizar.addItem("")
        self.cbx_tipo_doc_actualizar.addItem("")
        self.cbx_tipo_doc_actualizar.addItem("")
        self.horizontalLayout_4.addWidget(self.cbx_tipo_doc_actualizar)
        self.label_131 = QtWidgets.QLabel(self.groupBox)
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_4.addWidget(self.label_131)
        self.lne_nro_doc_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nro_doc_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_doc_actualizar.setText("")
        self.lne_nro_doc_actualizar.setObjectName("lne_nro_doc_actualizar")
        self.horizontalLayout_4.addWidget(self.lne_nro_doc_actualizar)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_4.addWidget(self.label_37)
        self.cbx_estado_actualizar = QtWidgets.QComboBox(self.groupBox)
        self.cbx_estado_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_estado_actualizar.setObjectName("cbx_estado_actualizar")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.addItem("")
        self.cbx_estado_actualizar.setItemText(6, "")
        self.horizontalLayout_4.addWidget(self.cbx_estado_actualizar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_123 = QtWidgets.QLabel(self.groupBox)
        self.label_123.setObjectName("label_123")
        self.horizontalLayout_5.addWidget(self.label_123)
        self.dte_nacimiento_actualizar = QtWidgets.QDateEdit(self.groupBox)
        self.dte_nacimiento_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_nacimiento_actualizar.setDate(QtCore.QDate(1945, 5, 17))
        self.dte_nacimiento_actualizar.setObjectName("dte_nacimiento_actualizar")
        self.horizontalLayout_5.addWidget(self.dte_nacimiento_actualizar)
        self.label_126 = QtWidgets.QLabel(self.groupBox)
        self.label_126.setObjectName("label_126")
        self.horizontalLayout_5.addWidget(self.label_126)
        self.cbx_estado_civil_actualizar = QtWidgets.QComboBox(self.groupBox)
        self.cbx_estado_civil_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_estado_civil_actualizar.setObjectName("cbx_estado_civil_actualizar")
        self.cbx_estado_civil_actualizar.addItem("")
        self.cbx_estado_civil_actualizar.addItem("")
        self.cbx_estado_civil_actualizar.addItem("")
        self.cbx_estado_civil_actualizar.addItem("")
        self.horizontalLayout_5.addWidget(self.cbx_estado_civil_actualizar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_147 = QtWidgets.QLabel(self.groupBox)
        self.label_147.setObjectName("label_147")
        self.horizontalLayout_6.addWidget(self.label_147)
        self.lne_domicilio_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_domicilio_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio_actualizar.setText("")
        self.lne_domicilio_actualizar.setObjectName("lne_domicilio_actualizar")
        self.horizontalLayout_6.addWidget(self.lne_domicilio_actualizar)
        self.label_124 = QtWidgets.QLabel(self.groupBox)
        self.label_124.setObjectName("label_124")
        self.horizontalLayout_6.addWidget(self.label_124)
        self.lne_barrio_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_barrio_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_barrio_actualizar.setText("")
        self.lne_barrio_actualizar.setObjectName("lne_barrio_actualizar")
        self.horizontalLayout_6.addWidget(self.lne_barrio_actualizar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_127 = QtWidgets.QLabel(self.groupBox)
        self.label_127.setObjectName("label_127")
        self.horizontalLayout_7.addWidget(self.label_127)
        self.lne_telefono_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_telefono_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_telefono_actualizar.setText("")
        self.lne_telefono_actualizar.setObjectName("lne_telefono_actualizar")
        self.horizontalLayout_7.addWidget(self.lne_telefono_actualizar)
        self.label_135 = QtWidgets.QLabel(self.groupBox)
        self.label_135.setObjectName("label_135")
        self.horizontalLayout_7.addWidget(self.label_135)
        self.cbx_ciudad_actualizar = QtWidgets.QComboBox(self.groupBox)
        self.cbx_ciudad_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ciudad_actualizar.setObjectName("cbx_ciudad_actualizar")
        self.cbx_ciudad_actualizar.addItem("")
        self.cbx_ciudad_actualizar.addItem("")
        self.cbx_ciudad_actualizar.addItem("")
        self.horizontalLayout_7.addWidget(self.cbx_ciudad_actualizar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_133 = QtWidgets.QLabel(self.groupBox)
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_8.addWidget(self.label_133)
        self.lne_limite_credito_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_limite_credito_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_limite_credito_actualizar.setText("")
        self.lne_limite_credito_actualizar.setObjectName("lne_limite_credito_actualizar")
        self.horizontalLayout_8.addWidget(self.lne_limite_credito_actualizar)
        self.label_130 = QtWidgets.QLabel(self.groupBox)
        self.label_130.setObjectName("label_130")
        self.horizontalLayout_8.addWidget(self.label_130)
        self.lne_email_actualizar = QtWidgets.QLineEdit(self.groupBox)
        self.lne_email_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_email_actualizar.setText("")
        self.lne_email_actualizar.setObjectName("lne_email_actualizar")
        self.horizontalLayout_8.addWidget(self.lne_email_actualizar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_132 = QtWidgets.QLabel(self.groupBox)
        self.label_132.setObjectName("label_132")
        self.verticalLayout.addWidget(self.label_132)
        self.txte_observaciones_actualizar = QtWidgets.QTextEdit(self.groupBox)
        self.txte_observaciones_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txte_observaciones_actualizar.setObjectName("txte_observaciones_actualizar")
        self.verticalLayout.addWidget(self.txte_observaciones_actualizar)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/tarjeta-personal-de-datos-de-contacto.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tab_widget_actualizar_cliente.addTab(self.tab_16, icon, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 1, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_140 = QtWidgets.QLabel(self.groupBox_2)
        self.label_140.setObjectName("label_140")
        self.horizontalLayout_9.addWidget(self.label_140)
        self.lne_ocupacion_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_ocupacion_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lne_ocupacion_actualizar.setText("")
        self.lne_ocupacion_actualizar.setObjectName("lne_ocupacion_actualizar")
        self.horizontalLayout_9.addWidget(self.lne_ocupacion_actualizar)
        self.label_137 = QtWidgets.QLabel(self.groupBox_2)
        self.label_137.setObjectName("label_137")
        self.horizontalLayout_9.addWidget(self.label_137)
        self.lne_sueldo_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_sueldo_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_sueldo_actualizar.setText("")
        self.lne_sueldo_actualizar.setObjectName("lne_sueldo_actualizar")
        self.horizontalLayout_9.addWidget(self.lne_sueldo_actualizar)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_139 = QtWidgets.QLabel(self.groupBox_2)
        self.label_139.setObjectName("label_139")
        self.horizontalLayout_10.addWidget(self.label_139)
        self.lne_organismo_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_organismo_actualizar.setMinimumSize(QtCore.QSize(200, 0))
        self.lne_organismo_actualizar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lne_organismo_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_organismo_actualizar.setText("")
        self.lne_organismo_actualizar.setObjectName("lne_organismo_actualizar")
        self.horizontalLayout_10.addWidget(self.lne_organismo_actualizar)
        self.label_145 = QtWidgets.QLabel(self.groupBox_2)
        self.label_145.setObjectName("label_145")
        self.horizontalLayout_10.addWidget(self.label_145)
        self.lne_antiguedad_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_antiguedad_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_antiguedad_actualizar.setText("")
        self.lne_antiguedad_actualizar.setObjectName("lne_antiguedad_actualizar")
        self.horizontalLayout_10.addWidget(self.lne_antiguedad_actualizar)
        self.label_143 = QtWidgets.QLabel(self.groupBox_2)
        self.label_143.setObjectName("label_143")
        self.horizontalLayout_10.addWidget(self.label_143)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_138 = QtWidgets.QLabel(self.groupBox_2)
        self.label_138.setObjectName("label_138")
        self.horizontalLayout_11.addWidget(self.label_138)
        self.lne_telefono_laboral_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_telefono_laboral_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_telefono_laboral_actualizar.setText("")
        self.lne_telefono_laboral_actualizar.setObjectName("lne_telefono_laboral_actualizar")
        self.horizontalLayout_11.addWidget(self.lne_telefono_laboral_actualizar)
        self.label_146 = QtWidgets.QLabel(self.groupBox_2)
        self.label_146.setObjectName("label_146")
        self.horizontalLayout_11.addWidget(self.label_146)
        self.lne_categoria_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_categoria_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_categoria_actualizar.setText("")
        self.lne_categoria_actualizar.setObjectName("lne_categoria_actualizar")
        self.horizontalLayout_11.addWidget(self.lne_categoria_actualizar)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_141 = QtWidgets.QLabel(self.groupBox_2)
        self.label_141.setObjectName("label_141")
        self.horizontalLayout_12.addWidget(self.label_141)
        self.lne_domicilio_laboral_actualizar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_domicilio_laboral_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio_laboral_actualizar.setText("")
        self.lne_domicilio_laboral_actualizar.setObjectName("lne_domicilio_laboral_actualizar")
        self.horizontalLayout_12.addWidget(self.lne_domicilio_laboral_actualizar)
        self.ckbx_recibo_sueldo_actualizar = QtWidgets.QCheckBox(self.groupBox_2)
        self.ckbx_recibo_sueldo_actualizar.setChecked(True)
        self.ckbx_recibo_sueldo_actualizar.setObjectName("ckbx_recibo_sueldo_actualizar")
        self.horizontalLayout_12.addWidget(self.ckbx_recibo_sueldo_actualizar)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem13, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/hombre-en-el-escritorio-de-la-oficina-con-un-ordenador.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tab_widget_actualizar_cliente.addTab(self.tab_17, icon1, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_19)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem14, 2, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem15, 4, 1, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_21.addWidget(self.label)
        self.lne_archivo = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_archivo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_archivo.setObjectName("lne_archivo")
        self.horizontalLayout_21.addWidget(self.lne_archivo)
        self.boton_archivo = QtWidgets.QPushButton(self.groupBox_4)
        self.boton_archivo.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_archivo.setObjectName("boton_archivo")
        self.horizontalLayout_21.addWidget(self.boton_archivo)
        self.boton_descargar = QtWidgets.QPushButton(self.groupBox_4)
        self.boton_descargar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_descargar.setObjectName("boton_descargar")
        self.horizontalLayout_21.addWidget(self.boton_descargar)
        self.gridLayout_11.addLayout(self.horizontalLayout_21, 3, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_13.addWidget(self.label_36)
        self.cbx_tipo_iva_actualizar = QtWidgets.QComboBox(self.groupBox_4)
        self.cbx_tipo_iva_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_tipo_iva_actualizar.setObjectName("cbx_tipo_iva_actualizar")
        self.cbx_tipo_iva_actualizar.addItem("")
        self.cbx_tipo_iva_actualizar.addItem("")
        self.cbx_tipo_iva_actualizar.addItem("")
        self.horizontalLayout_13.addWidget(self.cbx_tipo_iva_actualizar)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem16)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_160 = QtWidgets.QLabel(self.groupBox_4)
        self.label_160.setObjectName("label_160")
        self.horizontalLayout_15.addWidget(self.label_160)
        self.lne_cbu_actualizar = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cbu_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cbu_actualizar.setText("")
        self.lne_cbu_actualizar.setObjectName("lne_cbu_actualizar")
        self.horizontalLayout_15.addWidget(self.lne_cbu_actualizar)
        self.ckbx_veraz_actualizar = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_veraz_actualizar.setCheckable(True)
        self.ckbx_veraz_actualizar.setChecked(False)
        self.ckbx_veraz_actualizar.setObjectName("ckbx_veraz_actualizar")
        self.horizontalLayout_15.addWidget(self.ckbx_veraz_actualizar)
        self.gridLayout_5.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_161 = QtWidgets.QLabel(self.groupBox_4)
        self.label_161.setObjectName("label_161")
        self.horizontalLayout_16.addWidget(self.label_161)
        self.lne_nro_beneficio_actualizar = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_nro_beneficio_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nro_beneficio_actualizar.setText("")
        self.lne_nro_beneficio_actualizar.setObjectName("lne_nro_beneficio_actualizar")
        self.horizontalLayout_16.addWidget(self.lne_nro_beneficio_actualizar)
        self.ckbx_jub_pens_actualizar = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_jub_pens_actualizar.setObjectName("ckbx_jub_pens_actualizar")
        self.horizontalLayout_16.addWidget(self.ckbx_jub_pens_actualizar)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_159 = QtWidgets.QLabel(self.groupBox_4)
        self.label_159.setObjectName("label_159")
        self.horizontalLayout_14.addWidget(self.label_159)
        self.lne_cuit_actualizar = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cuit_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit_actualizar.setText("")
        self.lne_cuit_actualizar.setObjectName("lne_cuit_actualizar")
        self.horizontalLayout_14.addWidget(self.lne_cuit_actualizar)
        self.ckbx_facturas_actualizar = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_facturas_actualizar.setCheckable(True)
        self.ckbx_facturas_actualizar.setChecked(False)
        self.ckbx_facturas_actualizar.setObjectName("ckbx_facturas_actualizar")
        self.horizontalLayout_14.addWidget(self.ckbx_facturas_actualizar)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem17, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem18, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem19, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 0, 0, 2, 2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Íconos/casilla-y-boligrafo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tab_widget_actualizar_cliente.addTab(self.tab_19, icon2, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 3, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_51 = QtWidgets.QLabel(self.groupBox_3)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_17.addWidget(self.label_51)
        self.lne_garante_nro_doc_actualizar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_doc_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nro_doc_actualizar.setText("")
        self.lne_garante_nro_doc_actualizar.setObjectName("lne_garante_nro_doc_actualizar")
        self.horizontalLayout_17.addWidget(self.lne_garante_nro_doc_actualizar)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        self.lne_garante_nro_cliente_actualizar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_cliente_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nro_cliente_actualizar.setText("")
        self.lne_garante_nro_cliente_actualizar.setObjectName("lne_garante_nro_cliente_actualizar")
        self.horizontalLayout_17.addWidget(self.lne_garante_nro_cliente_actualizar)
        self.boton_buscar_garante_actualizar = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_buscar_garante_actualizar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_buscar_garante_actualizar.setObjectName("boton_buscar_garante_actualizar")
        self.horizontalLayout_17.addWidget(self.boton_buscar_garante_actualizar)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 0, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.txte_garante_observaciones_actualizar = QtWidgets.QTextEdit(self.groupBox_3)
        self.txte_garante_observaciones_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txte_garante_observaciones_actualizar.setObjectName("txte_garante_observaciones_actualizar")
        self.verticalLayout_4.addWidget(self.txte_garante_observaciones_actualizar)
        self.horizontalLayout_20.addLayout(self.verticalLayout_4)
        self.boton_agregar_actualizar = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_agregar_actualizar.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.boton_agregar_actualizar.setObjectName("boton_agregar_actualizar")
        self.horizontalLayout_20.addWidget(self.boton_agregar_actualizar)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 3, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.lne_garante_apellido_actualizar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_apellido_actualizar.setEnabled(False)
        self.lne_garante_apellido_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_apellido_actualizar.setText("")
        self.lne_garante_apellido_actualizar.setObjectName("lne_garante_apellido_actualizar")
        self.horizontalLayout_18.addWidget(self.lne_garante_apellido_actualizar)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.lne_garante_estado_actualizar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_estado_actualizar.setEnabled(False)
        self.lne_garante_estado_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_estado_actualizar.setText("")
        self.lne_garante_estado_actualizar.setObjectName("lne_garante_estado_actualizar")
        self.horizontalLayout_18.addWidget(self.lne_garante_estado_actualizar)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 1, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        self.lne_garante_nombre_actualizar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nombre_actualizar.setEnabled(False)
        self.lne_garante_nombre_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_garante_nombre_actualizar.setText("")
        self.lne_garante_nombre_actualizar.setObjectName("lne_garante_nombre_actualizar")
        self.horizontalLayout_19.addWidget(self.lne_garante_nombre_actualizar)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.cbx_tipo_garante_actualizar = QtWidgets.QComboBox(self.groupBox_3)
        self.cbx_tipo_garante_actualizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_tipo_garante_actualizar.setObjectName("cbx_tipo_garante_actualizar")
        self.cbx_tipo_garante_actualizar.addItem("")
        self.cbx_tipo_garante_actualizar.setItemText(0, "")
        self.cbx_tipo_garante_actualizar.addItem("")
        self.cbx_tipo_garante_actualizar.addItem("")
        self.cbx_tipo_garante_actualizar.addItem("")
        self.horizontalLayout_19.addWidget(self.cbx_tipo_garante_actualizar)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 2, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem21, 4, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem22, 4, 3, 1, 1)
        self.tw_garantes_lista = QtWidgets.QTableWidget(self.groupBox_3)
        self.tw_garantes_lista.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.tw_garantes_lista.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tw_garantes_lista.setObjectName("tw_garantes_lista")
        self.tw_garantes_lista.setColumnCount(6)
        self.tw_garantes_lista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tw_garantes_lista.setHorizontalHeaderItem(5, item)
        self.tw_garantes_lista.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout_4.addWidget(self.tw_garantes_lista, 4, 1, 1, 2)
        self.gridLayout_13.addWidget(self.groupBox_3, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Íconos/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tab_widget_actualizar_cliente.addTab(self.tab_18, icon3, "")
        self.gridLayout_3.addWidget(self.tab_widget_actualizar_cliente, 1, 0, 1, 2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Íconos/boton-actualizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon4, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form_clientes_actualizar)
        self.tabWidget.setCurrentIndex(0)
        self.tab_widget_actualizar_cliente.setCurrentIndex(0)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.txte_observaciones_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_email_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_limite_credito_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_telefono_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_domicilio_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_barrio_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_apellido_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_nro_doc_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_nombre_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_nro_cliente.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_ocupacion_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_organismo_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_telefono_laboral_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_domicilio_laboral_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_sueldo_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_antiguedad_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_categoria_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_garante_nro_doc_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_garante_nro_cliente_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.txte_garante_observaciones_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_cuit_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_cbu_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_nro_beneficio_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_garante_apellido_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_garante_estado_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_garante_nombre_actualizar.clear)
        self.boton_limpiar_actualizar_cliente.clicked.connect(self.lne_dni_filtro_actualizar.clear)
        QtCore.QMetaObject.connectSlotsByName(Form_clientes_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_dni_filtro_actualizar, self.boton_buscar_actualizar)
        Form_clientes_actualizar.setTabOrder(self.boton_buscar_actualizar, self.lne_apellido_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_apellido_actualizar, self.lne_nombre_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_nombre_actualizar, self.lne_nro_cliente)
        Form_clientes_actualizar.setTabOrder(self.lne_nro_cliente, self.cbx_tipo_doc_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_tipo_doc_actualizar, self.lne_nro_doc_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_nro_doc_actualizar, self.cbx_estado_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_estado_actualizar, self.dte_nacimiento_actualizar)
        Form_clientes_actualizar.setTabOrder(self.dte_nacimiento_actualizar, self.cbx_estado_civil_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_estado_civil_actualizar, self.lne_domicilio_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_domicilio_actualizar, self.lne_barrio_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_barrio_actualizar, self.lne_telefono_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_telefono_actualizar, self.cbx_ciudad_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_ciudad_actualizar, self.lne_limite_credito_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_limite_credito_actualizar, self.lne_email_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_email_actualizar, self.txte_observaciones_actualizar)
        Form_clientes_actualizar.setTabOrder(self.txte_observaciones_actualizar, self.lne_ocupacion_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_ocupacion_actualizar, self.lne_sueldo_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_sueldo_actualizar, self.lne_organismo_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_organismo_actualizar, self.lne_antiguedad_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_antiguedad_actualizar, self.lne_telefono_laboral_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_telefono_laboral_actualizar, self.lne_categoria_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_categoria_actualizar, self.lne_domicilio_laboral_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_domicilio_laboral_actualizar, self.ckbx_recibo_sueldo_actualizar)
        Form_clientes_actualizar.setTabOrder(self.ckbx_recibo_sueldo_actualizar, self.lne_cuit_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_cuit_actualizar, self.cbx_tipo_iva_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_tipo_iva_actualizar, self.ckbx_facturas_actualizar)
        Form_clientes_actualizar.setTabOrder(self.ckbx_facturas_actualizar, self.ckbx_veraz_actualizar)
        Form_clientes_actualizar.setTabOrder(self.ckbx_veraz_actualizar, self.lne_nro_beneficio_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_nro_beneficio_actualizar, self.lne_cbu_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_cbu_actualizar, self.tabWidget)
        Form_clientes_actualizar.setTabOrder(self.tabWidget, self.tab_widget_actualizar_cliente)
        Form_clientes_actualizar.setTabOrder(self.tab_widget_actualizar_cliente, self.ckbx_jub_pens_actualizar)
        Form_clientes_actualizar.setTabOrder(self.ckbx_jub_pens_actualizar, self.lne_garante_nro_doc_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_garante_nro_doc_actualizar, self.lne_garante_nro_cliente_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_garante_nro_cliente_actualizar, self.boton_buscar_garante_actualizar)
        Form_clientes_actualizar.setTabOrder(self.boton_buscar_garante_actualizar, self.lne_garante_apellido_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_garante_apellido_actualizar, self.lne_garante_estado_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_garante_estado_actualizar, self.lne_garante_nombre_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_garante_nombre_actualizar, self.cbx_tipo_garante_actualizar)
        Form_clientes_actualizar.setTabOrder(self.cbx_tipo_garante_actualizar, self.txte_garante_observaciones_actualizar)
        Form_clientes_actualizar.setTabOrder(self.txte_garante_observaciones_actualizar, self.boton_agregar_actualizar)
        Form_clientes_actualizar.setTabOrder(self.boton_agregar_actualizar, self.tw_garantes_lista)
        Form_clientes_actualizar.setTabOrder(self.tw_garantes_lista, self.lne_id_party_actualizar)
        Form_clientes_actualizar.setTabOrder(self.lne_id_party_actualizar, self.boton_limpiar_actualizar_cliente)
        Form_clientes_actualizar.setTabOrder(self.boton_limpiar_actualizar_cliente, self.boton_actualizar)

    def retranslateUi(self, Form_clientes_actualizar):
        _translate = QtCore.QCoreApplication.translate
        Form_clientes_actualizar.setWindowTitle(_translate("Form_clientes_actualizar", "Actualizar Cliente"))
        self.label_122.setText(_translate("Form_clientes_actualizar", "DNI:"))
        self.boton_buscar_actualizar.setText(_translate("Form_clientes_actualizar", "Buscar"))
        self.boton_limpiar_actualizar_cliente.setText(_translate("Form_clientes_actualizar", "Limpiar"))
        self.boton_actualizar.setText(_translate("Form_clientes_actualizar", "Actualizar"))
        self.label_134.setText(_translate("Form_clientes_actualizar", "Apellido:"))
        self.label_125.setText(_translate("Form_clientes_actualizar", "Nombre :"))
        self.label_129.setText(_translate("Form_clientes_actualizar", "N°  Cliente :"))
        self.label_128.setText(_translate("Form_clientes_actualizar", "Tipo Documento:"))
        self.cbx_tipo_doc_actualizar.setItemText(0, _translate("Form_clientes_actualizar", "DNI "))
        self.cbx_tipo_doc_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "CUIL"))
        self.cbx_tipo_doc_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "CUIT "))
        self.label_131.setText(_translate("Form_clientes_actualizar", "Número:"))
        self.label_37.setText(_translate("Form_clientes_actualizar", "Estado Persona"))
        self.cbx_estado_actualizar.setItemText(0, _translate("Form_clientes_actualizar", "Activo"))
        self.cbx_estado_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "Moroso"))
        self.cbx_estado_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "Inactivo"))
        self.cbx_estado_actualizar.setItemText(3, _translate("Form_clientes_actualizar", "Judicial"))
        self.cbx_estado_actualizar.setItemText(4, _translate("Form_clientes_actualizar", "Bloqueado"))
        self.cbx_estado_actualizar.setItemText(5, _translate("Form_clientes_actualizar", "Cupo Cubierto"))
        self.label_123.setText(_translate("Form_clientes_actualizar", "Fecha de Nacimiento:"))
        self.dte_nacimiento_actualizar.setDisplayFormat(_translate("Form_clientes_actualizar", "yyyy/M/dd"))
        self.label_126.setText(_translate("Form_clientes_actualizar", "Estado Civil:"))
        self.cbx_estado_civil_actualizar.setItemText(0, _translate("Form_clientes_actualizar", "Soltero/era"))
        self.cbx_estado_civil_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "Casado/ada"))
        self.cbx_estado_civil_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "Viudo/da"))
        self.cbx_estado_civil_actualizar.setItemText(3, _translate("Form_clientes_actualizar", "Divorsiado/ada"))
        self.label_147.setText(_translate("Form_clientes_actualizar", "Domicilio :"))
        self.label_124.setText(_translate("Form_clientes_actualizar", "Barrio:"))
        self.label_127.setText(_translate("Form_clientes_actualizar", "Teléfono:"))
        self.label_135.setText(_translate("Form_clientes_actualizar", "Ciudad:"))
        self.cbx_ciudad_actualizar.setItemText(0, _translate("Form_clientes_actualizar", "Viedma"))
        self.cbx_ciudad_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "Patagones"))
        self.cbx_ciudad_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "Otros"))
        self.label_133.setText(_translate("Form_clientes_actualizar", "Límite por Créditos:"))
        self.label_130.setText(_translate("Form_clientes_actualizar", "Email:"))
        self.label_132.setText(_translate("Form_clientes_actualizar", "Observaciones: "))
        self.tab_widget_actualizar_cliente.setTabText(self.tab_widget_actualizar_cliente.indexOf(self.tab_16), _translate("Form_clientes_actualizar", "Datos Personales"))
        self.label_140.setText(_translate("Form_clientes_actualizar", "Ocupación:"))
        self.label_137.setText(_translate("Form_clientes_actualizar", "Sueldo $:"))
        self.label_139.setText(_translate("Form_clientes_actualizar", "Organismo: "))
        self.label_145.setText(_translate("Form_clientes_actualizar", "Antigüedad Laboral:"))
        self.label_143.setText(_translate("Form_clientes_actualizar", "años"))
        self.label_138.setText(_translate("Form_clientes_actualizar", "Teléfono Laboral:"))
        self.label_146.setText(_translate("Form_clientes_actualizar", "Categoria Laboral:"))
        self.label_141.setText(_translate("Form_clientes_actualizar", "Domicilio Laboral:"))
        self.ckbx_recibo_sueldo_actualizar.setText(_translate("Form_clientes_actualizar", "Posee Recibo de Sueldo"))
        self.tab_widget_actualizar_cliente.setTabText(self.tab_widget_actualizar_cliente.indexOf(self.tab_17), _translate("Form_clientes_actualizar", "Datos laborales"))
        self.label.setText(_translate("Form_clientes_actualizar", "Nombre Archivo: "))
        self.boton_archivo.setText(_translate("Form_clientes_actualizar", "buscar"))
        self.boton_descargar.setText(_translate("Form_clientes_actualizar", "descargar"))
        self.label_36.setText(_translate("Form_clientes_actualizar", "Tipo IVA:"))
        self.cbx_tipo_iva_actualizar.setItemText(0, _translate("Form_clientes_actualizar", "Consumidor final"))
        self.cbx_tipo_iva_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "Monotributista"))
        self.cbx_tipo_iva_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "Responsable inscripto"))
        self.label_160.setText(_translate("Form_clientes_actualizar", "N° CBU:"))
        self.ckbx_veraz_actualizar.setText(_translate("Form_clientes_actualizar", "Figura en el Veraz"))
        self.label_161.setText(_translate("Form_clientes_actualizar", "N° Beneficio:"))
        self.ckbx_jub_pens_actualizar.setText(_translate("Form_clientes_actualizar", "Es Jubilado / Pensionado"))
        self.label_159.setText(_translate("Form_clientes_actualizar", "N° CUIT:"))
        self.ckbx_facturas_actualizar.setText(_translate("Form_clientes_actualizar", "Presentó Facturas de Luz, Gas"))
        self.tab_widget_actualizar_cliente.setTabText(self.tab_widget_actualizar_cliente.indexOf(self.tab_19), _translate("Form_clientes_actualizar", "Otros Datos"))
        self.label_51.setText(_translate("Form_clientes_actualizar", "Nro Documento:"))
        self.label_31.setText(_translate("Form_clientes_actualizar", "N°  Cliente :"))
        self.boton_buscar_garante_actualizar.setText(_translate("Form_clientes_actualizar", "Buscar"))
        self.label_22.setText(_translate("Form_clientes_actualizar", "Observaciones: "))
        self.txte_garante_observaciones_actualizar.setHtml(_translate("Form_clientes_actualizar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstOne\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a</p></body></html>"))
        self.boton_agregar_actualizar.setText(_translate("Form_clientes_actualizar", "Agregar"))
        self.label_29.setText(_translate("Form_clientes_actualizar", "Apellido:"))
        self.label_23.setText(_translate("Form_clientes_actualizar", "Estado :"))
        self.label_4.setText(_translate("Form_clientes_actualizar", "Nombre :"))
        self.label_24.setText(_translate("Form_clientes_actualizar", "Tipo Garante :"))
        self.cbx_tipo_garante_actualizar.setItemText(1, _translate("Form_clientes_actualizar", "Garante Principal"))
        self.cbx_tipo_garante_actualizar.setItemText(2, _translate("Form_clientes_actualizar", "Garante Secundario"))
        self.cbx_tipo_garante_actualizar.setItemText(3, _translate("Form_clientes_actualizar", "Otro Garante"))
        item = self.tw_garantes_lista.horizontalHeaderItem(0)
        item.setText(_translate("Form_clientes_actualizar", "Estado"))
        item = self.tw_garantes_lista.horizontalHeaderItem(1)
        item.setText(_translate("Form_clientes_actualizar", "Tipo Garante"))
        item = self.tw_garantes_lista.horizontalHeaderItem(2)
        item.setText(_translate("Form_clientes_actualizar", "Nro. Cliente"))
        item = self.tw_garantes_lista.horizontalHeaderItem(3)
        item.setText(_translate("Form_clientes_actualizar", "Apellido"))
        item = self.tw_garantes_lista.horizontalHeaderItem(4)
        item.setText(_translate("Form_clientes_actualizar", "Nombre"))
        item = self.tw_garantes_lista.horizontalHeaderItem(5)
        item.setText(_translate("Form_clientes_actualizar", "Número Documento"))
        self.tab_widget_actualizar_cliente.setTabText(self.tab_widget_actualizar_cliente.indexOf(self.tab_18), _translate("Form_clientes_actualizar", "Datos Garante"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_clientes_actualizar", "Actualizar Cliente"))

