# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_clientes_nuevo.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_clientes_nuevo(object):
    def setupUi(self, Form_clientes_nuevo):
        Form_clientes_nuevo.setObjectName("Form_clientes_nuevo")
        Form_clientes_nuevo.resize(1005, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_clientes_nuevo.sizePolicy().hasHeightForWidth())
        Form_clientes_nuevo.setSizePolicy(sizePolicy)
        Form_clientes_nuevo.setMinimumSize(QtCore.QSize(800, 450))
        Form_clientes_nuevo.setMaximumSize(QtCore.QSize(1600, 800))
        Form_clientes_nuevo.setStyleSheet("font: 75 10pt \"KacstOne\";\n"
"selection-background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(81, 1, 1);\n"
"selection-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form_clientes_nuevo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Form_clientes_nuevo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgba(136, 3, 3);\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.boton_limpiar_nuevo = QtWidgets.QPushButton(self.tab)
        self.boton_limpiar_nuevo.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"font: 75 10pt \"KacstOne\";\n"
"")
        self.boton_limpiar_nuevo.setObjectName("boton_limpiar_nuevo")
        self.horizontalLayout.addWidget(self.boton_limpiar_nuevo, 0, QtCore.Qt.AlignRight)
        self.boton_guardar_nuevo = QtWidgets.QPushButton(self.tab)
        self.boton_guardar_nuevo.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"font: 75 10pt \"KacstOne\";\n"
"")
        self.boton_guardar_nuevo.setObjectName("boton_guardar_nuevo")
        self.horizontalLayout.addWidget(self.boton_guardar_nuevo, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("border-color: rgb(144, 13, 13);\n"
"border-widht: 2px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_apellido = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_apellido.sizePolicy().hasHeightForWidth())
        self.lne_apellido.setSizePolicy(sizePolicy)
        self.lne_apellido.setText("")
        self.lne_apellido.setObjectName("lne_apellido")
        self.horizontalLayout_2.addWidget(self.lne_apellido)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lne_nombre_nuevo = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_nombre_nuevo.sizePolicy().hasHeightForWidth())
        self.lne_nombre_nuevo.setSizePolicy(sizePolicy)
        self.lne_nombre_nuevo.setText("")
        self.lne_nombre_nuevo.setObjectName("lne_nombre_nuevo")
        self.horizontalLayout_2.addWidget(self.lne_nombre_nuevo)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lne_nro_cliente = QtWidgets.QLineEdit(self.frame)
        self.lne_nro_cliente.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_nro_cliente.sizePolicy().hasHeightForWidth())
        self.lne_nro_cliente.setSizePolicy(sizePolicy)
        self.lne_nro_cliente.setText("")
        self.lne_nro_cliente.setObjectName("lne_nro_cliente")
        self.horizontalLayout_2.addWidget(self.lne_nro_cliente)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_50 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(125, 25))
        self.label_50.setMaximumSize(QtCore.QSize(125, 25))
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_3.addWidget(self.label_50)
        self.cbx_tipo_doc = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_tipo_doc.sizePolicy().hasHeightForWidth())
        self.cbx_tipo_doc.setSizePolicy(sizePolicy)
        self.cbx_tipo_doc.setObjectName("cbx_tipo_doc")
        self.cbx_tipo_doc.addItem("")
        self.cbx_tipo_doc.addItem("")
        self.cbx_tipo_doc.addItem("")
        self.horizontalLayout_3.addWidget(self.cbx_tipo_doc)
        self.label_49 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(75, 25))
        self.label_49.setMaximumSize(QtCore.QSize(75, 25))
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_3.addWidget(self.label_49)
        self.lne_nro_doc = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_nro_doc.sizePolicy().hasHeightForWidth())
        self.lne_nro_doc.setSizePolicy(sizePolicy)
        self.lne_nro_doc.setMinimumSize(QtCore.QSize(125, 25))
        self.lne_nro_doc.setMaximumSize(QtCore.QSize(125, 25))
        self.lne_nro_doc.setText("")
        self.lne_nro_doc.setObjectName("lne_nro_doc")
        self.horizontalLayout_3.addWidget(self.lne_nro_doc)
        self.label_37 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(125, 25))
        self.label_37.setMaximumSize(QtCore.QSize(125, 25))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_3.addWidget(self.label_37)
        self.cbx_estado = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_estado.sizePolicy().hasHeightForWidth())
        self.cbx_estado.setSizePolicy(sizePolicy)
        self.cbx_estado.setMinimumSize(QtCore.QSize(125, 25))
        self.cbx_estado.setMaximumSize(QtCore.QSize(125, 25))
        self.cbx_estado.setObjectName("cbx_estado")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.addItem("")
        self.cbx_estado.setItemText(6, "")
        self.horizontalLayout_3.addWidget(self.cbx_estado)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(150, 25))
        self.label_7.setMaximumSize(QtCore.QSize(150, 25))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.dte_nacimiento = QtWidgets.QDateEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_nacimiento.sizePolicy().hasHeightForWidth())
        self.dte_nacimiento.setSizePolicy(sizePolicy)
        self.dte_nacimiento.setMinimumSize(QtCore.QSize(100, 25))
        self.dte_nacimiento.setMaximumSize(QtCore.QSize(100, 25))
        self.dte_nacimiento.setMaximumDate(QtCore.QDate(7999, 12, 26))
        self.dte_nacimiento.setCalendarPopup(True)
        self.dte_nacimiento.setDate(QtCore.QDate(1945, 5, 17))
        self.dte_nacimiento.setObjectName("dte_nacimiento")
        self.horizontalLayout_4.addWidget(self.dte_nacimiento)
        self.label_13 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(100, 25))
        self.label_13.setMaximumSize(QtCore.QSize(100, 25))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.cbx_estado_civil = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_estado_civil.sizePolicy().hasHeightForWidth())
        self.cbx_estado_civil.setSizePolicy(sizePolicy)
        self.cbx_estado_civil.setObjectName("cbx_estado_civil")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.cbx_estado_civil.addItem("")
        self.horizontalLayout_4.addWidget(self.cbx_estado_civil)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lne_domicilio = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_domicilio.sizePolicy().hasHeightForWidth())
        self.lne_domicilio.setSizePolicy(sizePolicy)
        self.lne_domicilio.setMinimumSize(QtCore.QSize(250, 25))
        self.lne_domicilio.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_domicilio.setText("")
        self.lne_domicilio.setObjectName("lne_domicilio")
        self.horizontalLayout_5.addWidget(self.lne_domicilio)
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lne_barrio = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_barrio.sizePolicy().hasHeightForWidth())
        self.lne_barrio.setSizePolicy(sizePolicy)
        self.lne_barrio.setText("")
        self.lne_barrio.setObjectName("lne_barrio")
        self.horizontalLayout_5.addWidget(self.lne_barrio)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.lne_telefono = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_telefono.sizePolicy().hasHeightForWidth())
        self.lne_telefono.setSizePolicy(sizePolicy)
        self.lne_telefono.setMinimumSize(QtCore.QSize(150, 25))
        self.lne_telefono.setMaximumSize(QtCore.QSize(150, 25))
        self.lne_telefono.setText("")
        self.lne_telefono.setObjectName("lne_telefono")
        self.horizontalLayout_6.addWidget(self.lne_telefono)
        self.label_10 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.cbx_ciudad = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_ciudad.sizePolicy().hasHeightForWidth())
        self.cbx_ciudad.setSizePolicy(sizePolicy)
        self.cbx_ciudad.setMinimumSize(QtCore.QSize(100, 0))
        self.cbx_ciudad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbx_ciudad.setObjectName("cbx_ciudad")
        self.cbx_ciudad.addItem("")
        self.cbx_ciudad.addItem("")
        self.cbx_ciudad.addItem("")
        self.horizontalLayout_6.addWidget(self.cbx_ciudad)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lne_limite_credito = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_limite_credito.sizePolicy().hasHeightForWidth())
        self.lne_limite_credito.setSizePolicy(sizePolicy)
        self.lne_limite_credito.setText("")
        self.lne_limite_credito.setObjectName("lne_limite_credito")
        self.horizontalLayout_7.addWidget(self.lne_limite_credito)
        self.label_12 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.lne_email = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_email.sizePolicy().hasHeightForWidth())
        self.lne_email.setSizePolicy(sizePolicy)
        self.lne_email.setText("")
        self.lne_email.setObjectName("lne_email")
        self.horizontalLayout_7.addWidget(self.lne_email)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.txte_observaciones = QtWidgets.QTextEdit(self.frame)
        self.txte_observaciones.setObjectName("txte_observaciones")
        self.verticalLayout.addWidget(self.txte_observaciones)
        self.gridLayout.addLayout(self.verticalLayout, 6, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 6, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/tarjeta-personal-de-datos-de-contacto.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_4, icon, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.lne_organismo = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_organismo.setMaximumSize(QtCore.QSize(500, 22))
        self.lne_organismo.setText("")
        self.lne_organismo.setObjectName("lne_organismo")
        self.horizontalLayout_9.addWidget(self.lne_organismo)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.lne_antiguedad = QtWidgets.QDateEdit(self.groupBox_2)
        self.lne_antiguedad.setMinimumSize(QtCore.QSize(100, 0))
        self.lne_antiguedad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lne_antiguedad.setCalendarPopup(True)
        self.lne_antiguedad.setObjectName("lne_antiguedad")
        self.horizontalLayout_9.addWidget(self.lne_antiguedad)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.lne_telefono_laboral = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_telefono_laboral.setText("")
        self.lne_telefono_laboral.setObjectName("lne_telefono_laboral")
        self.horizontalLayout_10.addWidget(self.lne_telefono_laboral)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.lne_categoria = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_categoria.setText("")
        self.lne_categoria.setObjectName("lne_categoria")
        self.horizontalLayout_10.addWidget(self.lne_categoria)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        self.lne_domicilio_laboral = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_domicilio_laboral.setText("")
        self.lne_domicilio_laboral.setObjectName("lne_domicilio_laboral")
        self.horizontalLayout_11.addWidget(self.lne_domicilio_laboral)
        self.ckbx_recibo_sueldo_nuevo = QtWidgets.QCheckBox(self.groupBox_2)
        self.ckbx_recibo_sueldo_nuevo.setChecked(True)
        self.ckbx_recibo_sueldo_nuevo.setObjectName("ckbx_recibo_sueldo_nuevo")
        self.horizontalLayout_11.addWidget(self.ckbx_recibo_sueldo_nuevo)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 4, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 5, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.lne_ocupacion = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_ocupacion.setText("")
        self.lne_ocupacion.setObjectName("lne_ocupacion")
        self.horizontalLayout_8.addWidget(self.lne_ocupacion)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.lne_sueldo = QtWidgets.QLineEdit(self.groupBox_2)
        self.lne_sueldo.setObjectName("lne_sueldo")
        self.horizontalLayout_8.addWidget(self.lne_sueldo)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 2, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/hombre-en-el-escritorio-de-la-oficina-con-un-ordenador.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_5, icon1, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_12.addWidget(self.label_36)
        self.cbx_tipo_iva = QtWidgets.QComboBox(self.groupBox_4)
        self.cbx_tipo_iva.setObjectName("cbx_tipo_iva")
        self.cbx_tipo_iva.addItem("")
        self.cbx_tipo_iva.addItem("")
        self.cbx_tipo_iva.addItem("")
        self.horizontalLayout_12.addWidget(self.cbx_tipo_iva)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_13.addWidget(self.label_33)
        self.lne_cuit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.horizontalLayout_13.addWidget(self.lne_cuit)
        self.ckbx_facturas = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_facturas.setChecked(False)
        self.ckbx_facturas.setObjectName("ckbx_facturas")
        self.horizontalLayout_13.addWidget(self.ckbx_facturas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_14.addWidget(self.label_34)
        self.lne_cbu = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_cbu.setText("")
        self.lne_cbu.setObjectName("lne_cbu")
        self.horizontalLayout_14.addWidget(self.lne_cbu)
        self.ckbx_veraz = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_veraz.setChecked(False)
        self.ckbx_veraz.setObjectName("ckbx_veraz")
        self.horizontalLayout_14.addWidget(self.ckbx_veraz)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_15.addWidget(self.label_35)
        self.lne_nro_beneficio = QtWidgets.QLineEdit(self.groupBox_4)
        self.lne_nro_beneficio.setText("")
        self.lne_nro_beneficio.setObjectName("lne_nro_beneficio")
        self.horizontalLayout_15.addWidget(self.lne_nro_beneficio)
        self.ckbx_jub_pens = QtWidgets.QCheckBox(self.groupBox_4)
        self.ckbx_jub_pens.setObjectName("ckbx_jub_pens")
        self.horizontalLayout_15.addWidget(self.ckbx_jub_pens)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem16, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Íconos/casilla-y-boligrafo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_7, icon2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(253, 194, 179);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tw_garantes_lista = QtWidgets.QTableWidget(self.groupBox_3)
        self.tw_garantes_lista.setStyleSheet("background-color: rgb(235, 160, 143);\n"
"")
        self.tw_garantes_lista.setObjectName("tw_garantes_lista")
        self.tw_garantes_lista.setColumnCount(6)
        self.tw_garantes_lista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_garantes_lista.setHorizontalHeaderItem(5, item)
        self.tw_garantes_lista.horizontalHeader().setDefaultSectionSize(120)
        self.gridLayout_8.addWidget(self.tw_garantes_lista, 1, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_51 = QtWidgets.QLabel(self.groupBox_3)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_16.addWidget(self.label_51)
        self.lne_garante_nro_doc_nuevo = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_doc_nuevo.setText("")
        self.lne_garante_nro_doc_nuevo.setObjectName("lne_garante_nro_doc_nuevo")
        self.horizontalLayout_16.addWidget(self.lne_garante_nro_doc_nuevo)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        self.lne_garante_nro_cliente_nuevo = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nro_cliente_nuevo.setText("")
        self.lne_garante_nro_cliente_nuevo.setObjectName("lne_garante_nro_cliente_nuevo")
        self.horizontalLayout_16.addWidget(self.lne_garante_nro_cliente_nuevo)
        self.boton_buscar_garante_nuevo = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_buscar_garante_nuevo.setObjectName("boton_buscar_garante_nuevo")
        self.horizontalLayout_16.addWidget(self.boton_buscar_garante_nuevo)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_17.addWidget(self.label_29)
        self.lne_garante_apellido = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_apellido.setText("")
        self.lne_garante_apellido.setObjectName("lne_garante_apellido")
        self.horizontalLayout_17.addWidget(self.lne_garante_apellido)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.lne_garante_estado = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_estado.setText("")
        self.lne_garante_estado.setObjectName("lne_garante_estado")
        self.horizontalLayout_17.addWidget(self.lne_garante_estado)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        self.lne_garante_nombre = QtWidgets.QLineEdit(self.groupBox_3)
        self.lne_garante_nombre.setText("")
        self.lne_garante_nombre.setObjectName("lne_garante_nombre")
        self.horizontalLayout_18.addWidget(self.lne_garante_nombre)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_18.addWidget(self.label_24)
        self.cbx_tipo_garante = QtWidgets.QComboBox(self.groupBox_3)
        self.cbx_tipo_garante.setObjectName("cbx_tipo_garante")
        self.cbx_tipo_garante.addItem("")
        self.cbx_tipo_garante.addItem("")
        self.cbx_tipo_garante.addItem("")
        self.horizontalLayout_18.addWidget(self.cbx_tipo_garante)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.txte_garante_observaciones = QtWidgets.QTextEdit(self.groupBox_3)
        self.txte_garante_observaciones.setObjectName("txte_garante_observaciones")
        self.verticalLayout_3.addWidget(self.txte_garante_observaciones)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.boton_agregar_nuevo = QtWidgets.QPushButton(self.groupBox_3)
        self.boton_agregar_nuevo.setObjectName("boton_agregar_nuevo")
        self.verticalLayout_4.addWidget(self.boton_agregar_nuevo, 0, QtCore.Qt.AlignRight)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem17, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Íconos/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_2.addTab(self.tab_6, icon3, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Íconos/silueta-masculina-de-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon4, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form_clientes_nuevo)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_email.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_barrio.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_nro_cliente.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_nombre_nuevo.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_apellido.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_nro_doc.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_domicilio.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_telefono.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_limite_credito.clear)
        self.boton_limpiar_nuevo.clicked['bool'].connect(self.tw_garantes_lista.clearContents)
        self.boton_limpiar_nuevo.clicked['bool'].connect(self.tw_garantes_lista.reset)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_garante_nombre.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_garante_estado.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_garante_nro_cliente_nuevo.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_garante_nro_doc_nuevo.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_garante_apellido.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.txte_garante_observaciones.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_ocupacion.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_organismo.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_telefono_laboral.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_domicilio_laboral.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_sueldo.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_categoria.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_cuit.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_cbu.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.lne_nro_beneficio.clear)
        self.boton_limpiar_nuevo.clicked.connect(self.txte_observaciones.clear)
        self.pushButton.clicked.connect(self.lne_garante_nro_doc_nuevo.clear)
        self.pushButton.clicked.connect(self.lne_garante_apellido.clear)
        self.pushButton.clicked.connect(self.lne_garante_nombre.clear)
        self.pushButton.clicked.connect(self.lne_garante_estado.clear)
        self.pushButton.clicked.connect(self.lne_garante_nro_cliente_nuevo.clear)
        QtCore.QMetaObject.connectSlotsByName(Form_clientes_nuevo)
        Form_clientes_nuevo.setTabOrder(self.tabWidget, self.tabWidget_2)
        Form_clientes_nuevo.setTabOrder(self.tabWidget_2, self.lne_apellido)
        Form_clientes_nuevo.setTabOrder(self.lne_apellido, self.lne_nombre_nuevo)
        Form_clientes_nuevo.setTabOrder(self.lne_nombre_nuevo, self.lne_nro_cliente)
        Form_clientes_nuevo.setTabOrder(self.lne_nro_cliente, self.cbx_tipo_doc)
        Form_clientes_nuevo.setTabOrder(self.cbx_tipo_doc, self.lne_nro_doc)
        Form_clientes_nuevo.setTabOrder(self.lne_nro_doc, self.cbx_estado)
        Form_clientes_nuevo.setTabOrder(self.cbx_estado, self.dte_nacimiento)
        Form_clientes_nuevo.setTabOrder(self.dte_nacimiento, self.cbx_estado_civil)
        Form_clientes_nuevo.setTabOrder(self.cbx_estado_civil, self.lne_domicilio)
        Form_clientes_nuevo.setTabOrder(self.lne_domicilio, self.lne_barrio)
        Form_clientes_nuevo.setTabOrder(self.lne_barrio, self.lne_telefono)
        Form_clientes_nuevo.setTabOrder(self.lne_telefono, self.cbx_ciudad)
        Form_clientes_nuevo.setTabOrder(self.cbx_ciudad, self.lne_limite_credito)
        Form_clientes_nuevo.setTabOrder(self.lne_limite_credito, self.lne_email)
        Form_clientes_nuevo.setTabOrder(self.lne_email, self.txte_observaciones)
        Form_clientes_nuevo.setTabOrder(self.txte_observaciones, self.lne_ocupacion)
        Form_clientes_nuevo.setTabOrder(self.lne_ocupacion, self.lne_sueldo)
        Form_clientes_nuevo.setTabOrder(self.lne_sueldo, self.lne_organismo)
        Form_clientes_nuevo.setTabOrder(self.lne_organismo, self.lne_antiguedad)
        Form_clientes_nuevo.setTabOrder(self.lne_antiguedad, self.lne_telefono_laboral)
        Form_clientes_nuevo.setTabOrder(self.lne_telefono_laboral, self.lne_categoria)
        Form_clientes_nuevo.setTabOrder(self.lne_categoria, self.lne_domicilio_laboral)
        Form_clientes_nuevo.setTabOrder(self.lne_domicilio_laboral, self.ckbx_recibo_sueldo_nuevo)
        Form_clientes_nuevo.setTabOrder(self.ckbx_recibo_sueldo_nuevo, self.cbx_tipo_iva)
        Form_clientes_nuevo.setTabOrder(self.cbx_tipo_iva, self.lne_cuit)
        Form_clientes_nuevo.setTabOrder(self.lne_cuit, self.ckbx_facturas)
        Form_clientes_nuevo.setTabOrder(self.ckbx_facturas, self.lne_cbu)
        Form_clientes_nuevo.setTabOrder(self.lne_cbu, self.ckbx_veraz)
        Form_clientes_nuevo.setTabOrder(self.ckbx_veraz, self.lne_nro_beneficio)
        Form_clientes_nuevo.setTabOrder(self.lne_nro_beneficio, self.ckbx_jub_pens)
        Form_clientes_nuevo.setTabOrder(self.ckbx_jub_pens, self.lne_garante_nro_doc_nuevo)
        Form_clientes_nuevo.setTabOrder(self.lne_garante_nro_doc_nuevo, self.lne_garante_nro_cliente_nuevo)
        Form_clientes_nuevo.setTabOrder(self.lne_garante_nro_cliente_nuevo, self.boton_buscar_garante_nuevo)
        Form_clientes_nuevo.setTabOrder(self.boton_buscar_garante_nuevo, self.pushButton)
        Form_clientes_nuevo.setTabOrder(self.pushButton, self.lne_garante_apellido)
        Form_clientes_nuevo.setTabOrder(self.lne_garante_apellido, self.lne_garante_estado)
        Form_clientes_nuevo.setTabOrder(self.lne_garante_estado, self.lne_garante_nombre)
        Form_clientes_nuevo.setTabOrder(self.lne_garante_nombre, self.cbx_tipo_garante)
        Form_clientes_nuevo.setTabOrder(self.cbx_tipo_garante, self.txte_garante_observaciones)
        Form_clientes_nuevo.setTabOrder(self.txte_garante_observaciones, self.boton_agregar_nuevo)
        Form_clientes_nuevo.setTabOrder(self.boton_agregar_nuevo, self.tw_garantes_lista)
        Form_clientes_nuevo.setTabOrder(self.tw_garantes_lista, self.boton_limpiar_nuevo)
        Form_clientes_nuevo.setTabOrder(self.boton_limpiar_nuevo, self.boton_guardar_nuevo)

    def retranslateUi(self, Form_clientes_nuevo):
        _translate = QtCore.QCoreApplication.translate
        Form_clientes_nuevo.setWindowTitle(_translate("Form_clientes_nuevo", "Alta Cliente"))
        self.boton_limpiar_nuevo.setText(_translate("Form_clientes_nuevo", "Limpiar"))
        self.boton_guardar_nuevo.setText(_translate("Form_clientes_nuevo", "Guardar"))
        self.label_2.setText(_translate("Form_clientes_nuevo", "Apellido:"))
        self.label.setText(_translate("Form_clientes_nuevo", "Nombre :"))
        self.label_3.setText(_translate("Form_clientes_nuevo", "N°  Cliente :"))
        self.label_50.setText(_translate("Form_clientes_nuevo", "Tipo Documento:"))
        self.cbx_tipo_doc.setItemText(0, _translate("Form_clientes_nuevo", "DNI "))
        self.cbx_tipo_doc.setItemText(1, _translate("Form_clientes_nuevo", "CUIL"))
        self.cbx_tipo_doc.setItemText(2, _translate("Form_clientes_nuevo", "CUIT "))
        self.label_49.setText(_translate("Form_clientes_nuevo", "Número:"))
        self.label_37.setText(_translate("Form_clientes_nuevo", "Estado Persona"))
        self.cbx_estado.setItemText(0, _translate("Form_clientes_nuevo", "Activo"))
        self.cbx_estado.setItemText(1, _translate("Form_clientes_nuevo", "Moroso"))
        self.cbx_estado.setItemText(2, _translate("Form_clientes_nuevo", "Inactivo"))
        self.cbx_estado.setItemText(3, _translate("Form_clientes_nuevo", "Judicial"))
        self.cbx_estado.setItemText(4, _translate("Form_clientes_nuevo", "Bloqueado"))
        self.cbx_estado.setItemText(5, _translate("Form_clientes_nuevo", "Cupo Cubierto"))
        self.label_7.setText(_translate("Form_clientes_nuevo", "Fecha de Nacimiento:"))
        self.dte_nacimiento.setDisplayFormat(_translate("Form_clientes_nuevo", "dd/M/yyyy"))
        self.label_13.setText(_translate("Form_clientes_nuevo", "Estado Civil:"))
        self.cbx_estado_civil.setItemText(0, _translate("Form_clientes_nuevo", "Soltero/a"))
        self.cbx_estado_civil.setItemText(1, _translate("Form_clientes_nuevo", "Casado/a"))
        self.cbx_estado_civil.setItemText(2, _translate("Form_clientes_nuevo", "Viudo/a"))
        self.cbx_estado_civil.setItemText(3, _translate("Form_clientes_nuevo", "Divorsiado/a"))
        self.label_5.setText(_translate("Form_clientes_nuevo", "Domicilio:"))
        self.label_11.setText(_translate("Form_clientes_nuevo", "Barrio:"))
        self.label_8.setText(_translate("Form_clientes_nuevo", "Teléfono:"))
        self.label_10.setText(_translate("Form_clientes_nuevo", "Ciudad:"))
        self.cbx_ciudad.setItemText(0, _translate("Form_clientes_nuevo", "Patagones"))
        self.cbx_ciudad.setItemText(1, _translate("Form_clientes_nuevo", "Viedma"))
        self.cbx_ciudad.setItemText(2, _translate("Form_clientes_nuevo", "Otros"))
        self.label_6.setText(_translate("Form_clientes_nuevo", "Límite por Créditos:"))
        self.label_12.setText(_translate("Form_clientes_nuevo", "Email:"))
        self.label_9.setText(_translate("Form_clientes_nuevo", "Observaciones: "))
        self.txte_observaciones.setHtml(_translate("Form_clientes_nuevo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstOne\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; -qt-user-state:131073;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form_clientes_nuevo", "Datos Personales"))
        self.label_15.setText(_translate("Form_clientes_nuevo", "Organismo: "))
        self.label_18.setText(_translate("Form_clientes_nuevo", "Antigüedad Laboral:"))
        self.lne_antiguedad.setDisplayFormat(_translate("Form_clientes_nuevo", "dd/M/yyyy"))
        self.label_17.setText(_translate("Form_clientes_nuevo", "Teléfono Laboral:"))
        self.label_21.setText(_translate("Form_clientes_nuevo", "Categoría laboral: "))
        self.label_16.setText(_translate("Form_clientes_nuevo", "Domicilio Laboral:"))
        self.ckbx_recibo_sueldo_nuevo.setText(_translate("Form_clientes_nuevo", "Posee Recibo de Sueldo"))
        self.label_14.setText(_translate("Form_clientes_nuevo", "Empresa:"))
        self.label_19.setText(_translate("Form_clientes_nuevo", "Sueldo $:"))
        self.lne_sueldo.setText(_translate("Form_clientes_nuevo", "0"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form_clientes_nuevo", "Datos laborales"))
        self.label_36.setText(_translate("Form_clientes_nuevo", "Tipo IVA:"))
        self.cbx_tipo_iva.setItemText(0, _translate("Form_clientes_nuevo", "Consumidor final"))
        self.cbx_tipo_iva.setItemText(1, _translate("Form_clientes_nuevo", "Responsable inscripto"))
        self.cbx_tipo_iva.setItemText(2, _translate("Form_clientes_nuevo", "Monotributista"))
        self.label_33.setText(_translate("Form_clientes_nuevo", "N° CUIT/CUIL:"))
        self.ckbx_facturas.setText(_translate("Form_clientes_nuevo", "Presentó Facturas de Luz, Gas"))
        self.label_34.setText(_translate("Form_clientes_nuevo", "N° CBU:"))
        self.ckbx_veraz.setText(_translate("Form_clientes_nuevo", "Figura en el Veraz"))
        self.label_35.setText(_translate("Form_clientes_nuevo", "N° Beneficio:"))
        self.ckbx_jub_pens.setText(_translate("Form_clientes_nuevo", "Es Jubilado / Pensionado"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form_clientes_nuevo", "Otros Datos"))
        item = self.tw_garantes_lista.horizontalHeaderItem(0)
        item.setText(_translate("Form_clientes_nuevo", "Estado"))
        item = self.tw_garantes_lista.horizontalHeaderItem(1)
        item.setText(_translate("Form_clientes_nuevo", "Tipo Garante"))
        item = self.tw_garantes_lista.horizontalHeaderItem(2)
        item.setText(_translate("Form_clientes_nuevo", "Nro. Cliente"))
        item = self.tw_garantes_lista.horizontalHeaderItem(3)
        item.setText(_translate("Form_clientes_nuevo", "Apellido"))
        item = self.tw_garantes_lista.horizontalHeaderItem(4)
        item.setText(_translate("Form_clientes_nuevo", "Nombre"))
        item = self.tw_garantes_lista.horizontalHeaderItem(5)
        item.setText(_translate("Form_clientes_nuevo", "Número Documento"))
        self.label_51.setText(_translate("Form_clientes_nuevo", "Nro Documento:"))
        self.label_31.setText(_translate("Form_clientes_nuevo", "N°  Cliente :"))
        self.boton_buscar_garante_nuevo.setText(_translate("Form_clientes_nuevo", "Buscar"))
        self.pushButton.setText(_translate("Form_clientes_nuevo", "Limpiar Garante"))
        self.label_29.setText(_translate("Form_clientes_nuevo", "Apellido:"))
        self.label_23.setText(_translate("Form_clientes_nuevo", "Estado :"))
        self.label_4.setText(_translate("Form_clientes_nuevo", "Nombre :"))
        self.label_24.setText(_translate("Form_clientes_nuevo", "Tipo Garante :"))
        self.cbx_tipo_garante.setItemText(0, _translate("Form_clientes_nuevo", "Garante Principal"))
        self.cbx_tipo_garante.setItemText(1, _translate("Form_clientes_nuevo", "Garante Secundario"))
        self.cbx_tipo_garante.setItemText(2, _translate("Form_clientes_nuevo", "Otro Garante"))
        self.label_22.setText(_translate("Form_clientes_nuevo", "Observaciones: "))
        self.txte_garante_observaciones.setHtml(_translate("Form_clientes_nuevo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstOne\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a</p></body></html>"))
        self.boton_agregar_nuevo.setText(_translate("Form_clientes_nuevo", "Agregar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form_clientes_nuevo", "Datos Garante"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_clientes_nuevo", "Alta Persona"))

