# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_empresa_datos.ui'
#
# Created: Thu Oct 20 17:28:54 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_empresa_datos(object):
    def setupUi(self, Form_empresa_datos):
        Form_empresa_datos.setObjectName("Form_empresa_datos")
        Form_empresa_datos.resize(630, 543)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 231, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 103, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Form_empresa_datos.setPalette(palette)
        Form_empresa_datos.setMouseTracking(False)
        Form_empresa_datos.setStyleSheet("selection-background-color: rgb(255, 170, 127);\n"
"background-color: rgb(239, 235, 231);")
        self.boton_guardar = QtWidgets.QPushButton(Form_empresa_datos)
        self.boton_guardar.setGeometry(QtCore.QRect(559, 510, 61, 23))
        self.boton_guardar.setStyleSheet("background-color: rgb(251, 204, 193);\n"
"font:  10pt \"KacstOne\";")
        self.boton_guardar.setObjectName("boton_guardar")
        self.boton_limpiar = QtWidgets.QPushButton(Form_empresa_datos)
        self.boton_limpiar.setGeometry(QtCore.QRect(490, 510, 61, 23))
        self.boton_limpiar.setStyleSheet("background-color: rgb(251, 204, 193);\n"
"font:  10pt \"KacstOne\";")
        self.boton_limpiar.setObjectName("boton_limpiar")
        self.tabWidget = QtWidgets.QTabWidget(Form_empresa_datos)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 491))
        self.tabWidget.setStyleSheet("background-color: rgb(172, 55, 26);\n"
"font:  11pt \"KacstOne\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 571, 401))
        self.tabWidget_2.setStyleSheet("background-color: rgb(239, 235, 231);\n"
"font:  10pt \"KacstOne\";\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(24, 26, 521, 331))
        self.groupBox.setAcceptDrops(True)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgb(239, 235, 231);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(172, 55, 26);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(239, 235, 231);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDateEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lne_nombre = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nombre.setGeometry(QtCore.QRect(197, 27, 301, 20))
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lne_nombre.setFont(font)
        self.lne_nombre.setText("")
        self.lne_nombre.setObjectName("lne_nombre")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(27, 27, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(27, 57, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(27, 87, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(27, 117, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(27, 147, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(27, 177, 141, 16))
        self.label_8.setObjectName("label_8")
        self.lne_ciudad = QtWidgets.QLineEdit(self.groupBox)
        self.lne_ciudad.setGeometry(QtCore.QRect(197, 57, 171, 20))
        self.lne_ciudad.setText("")
        self.lne_ciudad.setObjectName("lne_ciudad")
        self.lne_direccion = QtWidgets.QLineEdit(self.groupBox)
        self.lne_direccion.setGeometry(QtCore.QRect(197, 87, 300, 20))
        self.lne_direccion.setText("")
        self.lne_direccion.setObjectName("lne_direccion")
        self.lne_telefono = QtWidgets.QLineEdit(self.groupBox)
        self.lne_telefono.setGeometry(QtCore.QRect(197, 117, 171, 20))
        self.lne_telefono.setText("")
        self.lne_telefono.setObjectName("lne_telefono")
        self.lne_email = QtWidgets.QLineEdit(self.groupBox)
        self.lne_email.setGeometry(QtCore.QRect(197, 147, 261, 20))
        self.lne_email.setText("")
        self.lne_email.setObjectName("lne_email")
        self.lne_website = QtWidgets.QLineEdit(self.groupBox)
        self.lne_website.setGeometry(QtCore.QRect(197, 177, 181, 20))
        self.lne_website.setText("")
        self.lne_website.setObjectName("lne_website")
        self.lne_ingresos_brutos = QtWidgets.QLineEdit(self.groupBox)
        self.lne_ingresos_brutos.setGeometry(QtCore.QRect(197, 237, 171, 20))
        self.lne_ingresos_brutos.setText("")
        self.lne_ingresos_brutos.setObjectName("lne_ingresos_brutos")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(27, 207, 141, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(27, 237, 141, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(27, 267, 141, 16))
        self.label_11.setObjectName("label_11")
        self.lne_cuit = QtWidgets.QLineEdit(self.groupBox)
        self.lne_cuit.setGeometry(QtCore.QRect(197, 267, 181, 20))
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.cbx_tipo_iva = QtWidgets.QComboBox(self.groupBox)
        self.cbx_tipo_iva.setGeometry(QtCore.QRect(197, 207, 171, 23))
        self.cbx_tipo_iva.setObjectName("cbx_tipo_iva")
        self.cbx_tipo_iva.addItem("")
        self.cbx_tipo_iva.addItem("")
        self.cbx_tipo_iva.addItem("")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(23, 297, 141, 16))
        self.label_12.setObjectName("label_12")
        self.lne_nombre_fantasia = QtWidgets.QLineEdit(self.groupBox)
        self.lne_nombre_fantasia.setGeometry(QtCore.QRect(198, 296, 181, 20))
        self.lne_nombre_fantasia.setText("")
        self.lne_nombre_fantasia.setObjectName("lne_nombre_fantasia")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/tarjeta-personal-de-datos-de-contacto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab, icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/hombre-en-el-escritorio-de-la-oficina-con-un-ordenador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")

        self.retranslateUi(Form_empresa_datos)
        self.tabWidget_2.setCurrentIndex(0)
        self.boton_limpiar.clicked.connect(self.lne_nombre.clear)
        self.boton_limpiar.clicked.connect(self.lne_ciudad.clear)
        self.boton_limpiar.clicked.connect(self.lne_direccion.clear)
        self.boton_limpiar.clicked.connect(self.lne_telefono.clear)
        self.boton_limpiar.clicked.connect(self.lne_email.clear)
        self.boton_limpiar.clicked.connect(self.lne_website.clear)
        self.boton_limpiar.clicked.connect(self.lne_ingresos_brutos.clear)
        self.boton_limpiar.clicked.connect(self.lne_cuit.clear)
        self.boton_limpiar.clicked.connect(self.lne_nombre_fantasia.clear)
        QtCore.QMetaObject.connectSlotsByName(Form_empresa_datos)

    def retranslateUi(self, Form_empresa_datos):
        _translate = QtCore.QCoreApplication.translate
        Form_empresa_datos.setWindowTitle(_translate("Form_empresa_datos", "Alta Empresa"))
        self.boton_guardar.setText(_translate("Form_empresa_datos", "Guardar"))
        self.boton_limpiar.setText(_translate("Form_empresa_datos", "Limpiar"))
        self.label_3.setText(_translate("Form_empresa_datos", "Nombre de la Empresa:"))
        self.label_4.setText(_translate("Form_empresa_datos", "Ciudad:"))
        self.label_5.setText(_translate("Form_empresa_datos", "Dirección:"))
        self.label_6.setText(_translate("Form_empresa_datos", "Teléfono/Fax:"))
        self.label_7.setText(_translate("Form_empresa_datos", "E-mail:"))
        self.label_8.setText(_translate("Form_empresa_datos", "Website:"))
        self.label_9.setText(_translate("Form_empresa_datos", "Tipo de IVA:"))
        self.label_10.setText(_translate("Form_empresa_datos", "Ingresos Brutos:"))
        self.label_11.setText(_translate("Form_empresa_datos", "N° de CUIT:"))
        self.cbx_tipo_iva.setItemText(0, _translate("Form_empresa_datos", "Responsable inscripto"))
        self.cbx_tipo_iva.setItemText(1, _translate("Form_empresa_datos", "Exento"))
        self.cbx_tipo_iva.setItemText(2, _translate("Form_empresa_datos", "Monotributo"))
        self.label_12.setText(_translate("Form_empresa_datos", "Nombre de  fantasia"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form_empresa_datos", "Datos de la Empresa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form_empresa_datos", "Empresa"))

