# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 199, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 199, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 178, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 199, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 144, 89))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 51, 12))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 68, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 102, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("KacstOne")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgb(226, 226, 226);\n"
"font:  10pt \"KacstOne\";\n"
"selection-background-color: rgb(149, 148, 142);\n"
"selection-color: rgb(4, 4, 4);\n"
"")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 205, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 205, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 205, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.centralWidget.setPalette(palette)
        self.centralWidget.setStyleSheet("selection-background-color: rgb(248, 205, 196);")
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"background-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:0.487, y2:0.977273, stop:0.188482 rgba(132, 0, 0, 255), stop:1 rgba(235, 0, 4, 255));\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-color: rgb(255,255,255);\n"
"border-radius: 8px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(585, 127, 504, 145))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.46, y1:0, x2:0.487, y2:0.977273, stop:0.188482 rgba(132, 0, 0, 255), stop:1 rgba(235, 0, 4, 255));\n"
"border-top-color: rgb(138, 0, 0);\n"
"border-left-color: rgb(174, 0, 2);\n"
"border-bottom-color: rgb(204, 0, 3);\n"
"\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Íconos/credi1.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(1002, 392, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 25))
        self.label.setMaximumSize(QtCore.QSize(150, 25))
        self.label.setStyleSheet("background-color: rgb(231, 0, 4);\n"
"border-top-color: rgb(231, 0, 4);\n"
"border-left-color: rgb(231, 0, 4);\n"
"border-bottom-color: rgb(231, 0, 4);\n"
"border-right-color: rgb(231, 0, 4);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Íconos/slam1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 330, 131, 81))
        self.pushButton.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"border_widht: 2px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-left-color: rgb(0, 0, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/icono-de-una-tuerca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1178, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.menuBar.setPalette(palette)
        self.menuBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuBar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.menuBar.setObjectName("menuBar")
        self.menuARCHIVO = QtWidgets.QMenu(self.menuBar)
        self.menuARCHIVO.setObjectName("menuARCHIVO")
        self.menuOPERACIONES = QtWidgets.QMenu(self.menuBar)
        self.menuOPERACIONES.setObjectName("menuOPERACIONES")
        self.menuAYUDA = QtWidgets.QMenu(self.menuBar)
        self.menuAYUDA.setObjectName("menuAYUDA")
        self.menuCLIENTE = QtWidgets.QMenu(self.menuBar)
        self.menuCLIENTE.setObjectName("menuCLIENTE")
        self.menuCR_DITOS = QtWidgets.QMenu(self.menuBar)
        self.menuCR_DITOS.setObjectName("menuCR_DITOS")
        self.menuCUOTAS = QtWidgets.QMenu(self.menuBar)
        self.menuCUOTAS.setObjectName("menuCUOTAS")
        self.menuCAJA = QtWidgets.QMenu(self.menuBar)
        self.menuCAJA.setObjectName("menuCAJA")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 148, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(4, 4, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.toolBar.setPalette(palette)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCONFIGURAR_OPCIONES = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/icono-de-una-tuerca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../Escritorio/Iconos/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCONFIGURAR_OPCIONES.setIcon(icon1)
        self.actionCONFIGURAR_OPCIONES.setObjectName("actionCONFIGURAR_OPCIONES")
        self.actionCLIENTES = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Íconos/silueta-masculina-de-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCLIENTES.setIcon(icon2)
        self.actionCLIENTES.setObjectName("actionCLIENTES")
        self.actionCOBRADORES = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Íconos/foto-principal-del-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCOBRADORES.setIcon(icon3)
        self.actionCOBRADORES.setObjectName("actionCOBRADORES")
        self.action_credito_agregar_nuevo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Íconos/icon(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_credito_agregar_nuevo.setIcon(icon4)
        self.action_credito_agregar_nuevo.setObjectName("action_credito_agregar_nuevo")
        self.actionGENERADOR_CA_DA_DE_PR_STAMOS = QtWidgets.QAction(MainWindow)
        self.actionGENERADOR_CA_DA_DE_PR_STAMOS.setObjectName("actionGENERADOR_CA_DA_DE_PR_STAMOS")
        self.actionREGLAS_OTORGACI_N_DE_CR_DITOS = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Íconos/documento-financiero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionREGLAS_OTORGACI_N_DE_CR_DITOS.setIcon(icon5)
        self.actionREGLAS_OTORGACI_N_DE_CR_DITOS.setObjectName("actionREGLAS_OTORGACI_N_DE_CR_DITOS")
        self.actionREGLAS_EMISI_N_DE_CR_DITOS = QtWidgets.QAction(MainWindow)
        self.actionREGLAS_EMISI_N_DE_CR_DITOS.setIcon(icon5)
        self.actionREGLAS_EMISI_N_DE_CR_DITOS.setObjectName("actionREGLAS_EMISI_N_DE_CR_DITOS")
        self.actionREPORTE_DE_CR_DITOS = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Íconos/casilla-y-boligrafo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionREPORTE_DE_CR_DITOS.setIcon(icon6)
        self.actionREPORTE_DE_CR_DITOS.setObjectName("actionREPORTE_DE_CR_DITOS")
        self.actionHist_cred_y_ctas = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Íconos/documento-financiero.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHist_cred_y_ctas.setIcon(icon7)
        self.actionHist_cred_y_ctas.setObjectName("actionHist_cred_y_ctas")
        self.actionBAJA_CR_DITOS = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Íconos/basura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBAJA_CR_DITOS.setIcon(icon8)
        self.actionBAJA_CR_DITOS.setObjectName("actionBAJA_CR_DITOS")
        self.actionMODIFICACI_N_DE_CR_DITOS = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Íconos/boton-actualizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMODIFICACI_N_DE_CR_DITOS.setIcon(icon9)
        self.actionMODIFICACI_N_DE_CR_DITOS.setObjectName("actionMODIFICACI_N_DE_CR_DITOS")
        self.actionREPORTE_DE_CUOTAS = QtWidgets.QAction(MainWindow)
        self.actionREPORTE_DE_CUOTAS.setIcon(icon6)
        self.actionREPORTE_DE_CUOTAS.setObjectName("actionREPORTE_DE_CUOTAS")
        self.actionCOBRAR_CUOTAS = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Íconos/maquina-de-facturacion-electronica-con-escaner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCOBRAR_CUOTAS.setIcon(icon10)
        self.actionCOBRAR_CUOTAS.setObjectName("actionCOBRAR_CUOTAS")
        self.actionPUNITORIOS_DE_CUOTAS = QtWidgets.QAction(MainWindow)
        self.actionPUNITORIOS_DE_CUOTAS.setObjectName("actionPUNITORIOS_DE_CUOTAS")
        self.actionGENERADOR_DE_COMISIONES = QtWidgets.QAction(MainWindow)
        self.actionGENERADOR_DE_COMISIONES.setObjectName("actionGENERADOR_DE_COMISIONES")
        self.actionREFINANCIAMIENTO = QtWidgets.QAction(MainWindow)
        self.actionREFINANCIAMIENTO.setIcon(icon5)
        self.actionREFINANCIAMIENTO.setObjectName("actionREFINANCIAMIENTO")
        self.actionCONSULTA_DEUDORES = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Íconos/signo-de-interrogacion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCONSULTA_DEUDORES.setIcon(icon11)
        self.actionCONSULTA_DEUDORES.setObjectName("actionCONSULTA_DEUDORES")
        self.actionREPORTE_DEUDORES = QtWidgets.QAction(MainWindow)
        self.actionREPORTE_DEUDORES.setIcon(icon6)
        self.actionREPORTE_DEUDORES.setObjectName("actionREPORTE_DEUDORES")
        self.actionGR_FICOS = QtWidgets.QAction(MainWindow)
        self.actionGR_FICOS.setObjectName("actionGR_FICOS")
        self.actionCONTENIDOS = QtWidgets.QAction(MainWindow)
        self.actionCONTENIDOS.setObjectName("actionCONTENIDOS")
        self.actionSITIOS_WEB = QtWidgets.QAction(MainWindow)
        self.actionSITIOS_WEB.setObjectName("actionSITIOS_WEB")
        self.actionCONFIGURACI_N_DE_OPCIONES = QtWidgets.QAction(MainWindow)
        self.actionCONFIGURACI_N_DE_OPCIONES.setIcon(icon1)
        self.actionCONFIGURACI_N_DE_OPCIONES.setObjectName("actionCONFIGURACI_N_DE_OPCIONES")
        self.action_buscar_cliente = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Íconos/prismaticos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_buscar_cliente.setIcon(icon12)
        self.action_buscar_cliente.setObjectName("action_buscar_cliente")
        self.actionUsuarios = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Íconos/llave-de-administrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUsuarios.setIcon(icon13)
        self.actionUsuarios.setObjectName("actionUsuarios")
        self.actionUsu = QtWidgets.QAction(MainWindow)
        self.actionUsu.setIcon(icon13)
        self.actionUsu.setObjectName("actionUsu")
        self.action_cliente_actualizar = QtWidgets.QAction(MainWindow)
        self.action_cliente_actualizar.setIcon(icon2)
        self.action_cliente_actualizar.setObjectName("action_cliente_actualizar")
        self.actionCobradores = QtWidgets.QAction(MainWindow)
        self.actionCobradores.setIcon(icon3)
        self.actionCobradores.setObjectName("actionCobradores")
        self.actionEmpresa = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Íconos/hombre-en-el-escritorio-de-la-oficina-con-un-ordenador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmpresa.setIcon(icon14)
        self.actionEmpresa.setObjectName("actionEmpresa")
        self.action_alta_cliente_nuevo = QtWidgets.QAction(MainWindow)
        self.action_alta_cliente_nuevo.setIcon(icon2)
        self.action_alta_cliente_nuevo.setObjectName("action_alta_cliente_nuevo")
        self.actionEmpresaActualizar = QtWidgets.QAction(MainWindow)
        self.actionEmpresaActualizar.setIcon(icon9)
        self.actionEmpresaActualizar.setObjectName("actionEmpresaActualizar")
        self.actionBUSCAR_REGISTRO = QtWidgets.QAction(MainWindow)
        self.actionBUSCAR_REGISTRO.setObjectName("actionBUSCAR_REGISTRO")
        self.actionGENERAR_REGISTRO = QtWidgets.QAction(MainWindow)
        self.actionGENERAR_REGISTRO.setObjectName("actionGENERAR_REGISTRO")
        self.actionINGRESOS_POR_PUNITORIOS = QtWidgets.QAction(MainWindow)
        self.actionINGRESOS_POR_PUNITORIOS.setObjectName("actionINGRESOS_POR_PUNITORIOS")
        self.actionHISTORIAL_GARANTE = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Íconos/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap("Íconos/herramientas-de-papel-y-lapiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHISTORIAL_GARANTE.setIcon(icon15)
        self.actionHISTORIAL_GARANTE.setObjectName("actionHISTORIAL_GARANTE")
        self.actionEgresos = QtWidgets.QAction(MainWindow)
        self.actionEgresos.setIcon(icon10)
        self.actionEgresos.setObjectName("actionEgresos")
        self.actionIngresos = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Íconos/maquina-de-facturacion-electronica-con-escaner.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionIngresos.setIcon(icon16)
        self.actionIngresos.setObjectName("actionIngresos")
        self.actionCALCULADOR = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Íconos/calculadora.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCALCULADOR.setIcon(icon17)
        self.actionCALCULADOR.setObjectName("actionCALCULADOR")
        self.actionUsu_Act = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Íconos/boton-actualizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionUsu_Act.setIcon(icon18)
        self.actionUsu_Act.setObjectName("actionUsu_Act")
        self.actionGenerador_punitorios = QtWidgets.QAction(MainWindow)
        self.actionGenerador_punitorios.setIcon(icon17)
        self.actionGenerador_punitorios.setObjectName("actionGenerador_punitorios")
        self.actionReparar_Cuotas = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Íconos/icono-de-una-tuerca.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionReparar_Cuotas.setIcon(icon19)
        self.actionReparar_Cuotas.setObjectName("actionReparar_Cuotas")
        self.actionBuscar_por_Apellido = QtWidgets.QAction(MainWindow)
        self.actionBuscar_por_Apellido.setIcon(icon12)
        self.actionBuscar_por_Apellido.setObjectName("actionBuscar_por_Apellido")
        self.actionBuscar_apellido = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Íconos/prismaticos.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionBuscar_apellido.setIcon(icon20)
        self.actionBuscar_apellido.setObjectName("actionBuscar_apellido")
        self.actionRefinanciar = QtWidgets.QAction(MainWindow)
        self.actionRefinanciar.setIcon(icon10)
        self.actionRefinanciar.setObjectName("actionRefinanciar")
        self.actionCalcular_Creditos = QtWidgets.QAction(MainWindow)
        self.actionCalcular_Creditos.setIcon(icon17)
        self.actionCalcular_Creditos.setObjectName("actionCalcular_Creditos")
        self.actionReporte_deuda_cliente = QtWidgets.QAction(MainWindow)
        self.actionReporte_deuda_cliente.setObjectName("actionReporte_deuda_cliente")
        self.menuARCHIVO.addAction(self.actionUsu)
        self.menuARCHIVO.addAction(self.actionUsu_Act)
        self.menuARCHIVO.addAction(self.actionEmpresa)
        self.menuARCHIVO.addAction(self.actionEmpresaActualizar)
        self.menuOPERACIONES.addAction(self.actionREPORTE_DE_CUOTAS)
        self.menuOPERACIONES.addAction(self.actionReporte_deuda_cliente)
        self.menuAYUDA.addAction(self.actionCONTENIDOS)
        self.menuAYUDA.addAction(self.actionSITIOS_WEB)
        self.menuCLIENTE.addAction(self.action_alta_cliente_nuevo)
        self.menuCLIENTE.addAction(self.action_cliente_actualizar)
        self.menuCLIENTE.addAction(self.action_buscar_cliente)
        self.menuCLIENTE.addAction(self.actionHISTORIAL_GARANTE)
        self.menuCLIENTE.addAction(self.actionBuscar_apellido)
        self.menuCR_DITOS.addAction(self.action_credito_agregar_nuevo)
        self.menuCR_DITOS.addAction(self.actionHist_cred_y_ctas)
        self.menuCR_DITOS.addAction(self.actionCalcular_Creditos)
        self.menuCR_DITOS.addAction(self.actionRefinanciar)
        self.menuCUOTAS.addAction(self.actionCOBRAR_CUOTAS)
        self.menuCUOTAS.addAction(self.actionGenerador_punitorios)
        self.menuCUOTAS.addAction(self.actionReparar_Cuotas)
        self.menuCAJA.addAction(self.actionEgresos)
        self.menuCAJA.addAction(self.actionIngresos)
        self.menuBar.addAction(self.menuCLIENTE.menuAction())
        self.menuBar.addAction(self.menuCR_DITOS.menuAction())
        self.menuBar.addAction(self.menuCUOTAS.menuAction())
        self.menuBar.addAction(self.menuCAJA.menuAction())
        self.menuBar.addAction(self.menuOPERACIONES.menuAction())
        self.menuBar.addAction(self.menuARCHIVO.menuAction())
        self.menuBar.addAction(self.menuAYUDA.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_alta_cliente_nuevo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_credito_agregar_nuevo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCOBRAR_CUOTAS)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCALCULADOR)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inicio"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Configuración</p></body></html>"))
        self.menuARCHIVO.setTitle(_translate("MainWindow", "ARCHIVO"))
        self.menuOPERACIONES.setTitle(_translate("MainWindow", "REPORTES"))
        self.menuAYUDA.setTitle(_translate("MainWindow", "AYUDA"))
        self.menuCLIENTE.setTitle(_translate("MainWindow", "CLIENTE"))
        self.menuCR_DITOS.setTitle(_translate("MainWindow", "CRÈDITOS"))
        self.menuCUOTAS.setTitle(_translate("MainWindow", "CUOTAS"))
        self.menuCAJA.setTitle(_translate("MainWindow", "CAJA"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cliente</p></body></html>"))
        self.actionCONFIGURAR_OPCIONES.setText(_translate("MainWindow", "CONFIGURAR OPCIONES"))
        self.actionCLIENTES.setText(_translate("MainWindow", "CLIENTES"))
        self.actionCOBRADORES.setText(_translate("MainWindow", "Cobradores"))
        self.action_credito_agregar_nuevo.setText(_translate("MainWindow", "Agregar Nuevos Créditos"))
        self.actionGENERADOR_CA_DA_DE_PR_STAMOS.setText(_translate("MainWindow", "GENERADOR CAÍDA DE PRÉSTAMOS"))
        self.actionREGLAS_OTORGACI_N_DE_CR_DITOS.setText(_translate("MainWindow", "REGLAS OTORGACIÓN DE CRÉDITOS"))
        self.actionREGLAS_EMISI_N_DE_CR_DITOS.setText(_translate("MainWindow", "REGLAS EMISIÓN DE CRÉDITOS"))
        self.actionREPORTE_DE_CR_DITOS.setText(_translate("MainWindow", "REPORTE DE CRÉDITOS"))
        self.actionHist_cred_y_ctas.setText(_translate("MainWindow", "Historial Créditos y Cuotas"))
        self.actionBAJA_CR_DITOS.setText(_translate("MainWindow", "BAJA CRÉDITOS"))
        self.actionMODIFICACI_N_DE_CR_DITOS.setText(_translate("MainWindow", "MODIFICACIÓN DE CRÉDITOS"))
        self.actionREPORTE_DE_CUOTAS.setText(_translate("MainWindow", "Generador de Cuotas Vencidas"))
        self.actionCOBRAR_CUOTAS.setText(_translate("MainWindow", "Cobrar Cuotas"))
        self.actionPUNITORIOS_DE_CUOTAS.setText(_translate("MainWindow", "PUNITORIOS"))
        self.actionGENERADOR_DE_COMISIONES.setText(_translate("MainWindow", "GENERADOR DE COMISIONES"))
        self.actionREFINANCIAMIENTO.setText(_translate("MainWindow", "REFINANCIAMIENTO"))
        self.actionCONSULTA_DEUDORES.setText(_translate("MainWindow", "Consulta Deudores"))
        self.actionREPORTE_DEUDORES.setText(_translate("MainWindow", "REPORTE DEUDORES"))
        self.actionGR_FICOS.setText(_translate("MainWindow", "GRÁFICOS"))
        self.actionCONTENIDOS.setText(_translate("MainWindow", "CONTENIDOS"))
        self.actionSITIOS_WEB.setText(_translate("MainWindow", "SITIOS WEB"))
        self.actionCONFIGURACI_N_DE_OPCIONES.setText(_translate("MainWindow", "Configuración de Opciones"))
        self.action_buscar_cliente.setText(_translate("MainWindow", "Buscar Clientes"))
        self.actionUsuarios.setText(_translate("MainWindow", "Usuarios"))
        self.actionUsu.setText(_translate("MainWindow", "Usuarios"))
        self.action_cliente_actualizar.setText(_translate("MainWindow", "Actualizar Cliente"))
        self.actionCobradores.setText(_translate("MainWindow", "Cobradores"))
        self.actionEmpresa.setText(_translate("MainWindow", "Empresa"))
        self.action_alta_cliente_nuevo.setText(_translate("MainWindow", "Cliente Nuevo"))
        self.actionEmpresaActualizar.setText(_translate("MainWindow", "Empresa Actualizar"))
        self.actionBUSCAR_REGISTRO.setText(_translate("MainWindow", "GENERAR REGISTRO"))
        self.actionGENERAR_REGISTRO.setText(_translate("MainWindow", "GENERAR REGISTRO"))
        self.actionINGRESOS_POR_PUNITORIOS.setText(_translate("MainWindow", "INGRESOS POR PUNITORIOS"))
        self.actionHISTORIAL_GARANTE.setText(_translate("MainWindow", "Historial Garantes"))
        self.actionEgresos.setText(_translate("MainWindow", "Egresos"))
        self.actionIngresos.setText(_translate("MainWindow", "Ingresos"))
        self.actionCALCULADOR.setText(_translate("MainWindow", "Calculador"))
        self.actionUsu_Act.setText(_translate("MainWindow", "Usuario Actualizar"))
        self.actionGenerador_punitorios.setText(_translate("MainWindow", "Generador de Punitorios"))
        self.actionReparar_Cuotas.setText(_translate("MainWindow", "Reparar Cuotas"))
        self.actionBuscar_por_Apellido.setText(_translate("MainWindow", "Buscar por Apellido"))
        self.actionBuscar_apellido.setText(_translate("MainWindow", "Buscar por Apellido"))
        self.actionRefinanciar.setText(_translate("MainWindow", "Refinanciar"))
        self.actionCalcular_Creditos.setText(_translate("MainWindow", "Calcular Créditos"))
        self.actionReporte_deuda_cliente.setText(_translate("MainWindow", "Reporte deuda por cliente"))

